use std::cell::Cell;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::rc::Rc;

use md_first_core::{Context, Dispatcher, Preprocessor};
use md_first_preprocessor::rust_header::RustHeader;
use proc_macro2::TokenStream;

struct Project(tempfile::TempDir);

impl Project {
    fn new() -> Self {
        let project = Self(tempfile::tempdir().unwrap());
        project.write(
            "Cargo.toml",
            r#"
[workspace]
[workspace.metadata.md-first]
include = ["docs/**/*.md", "docs/a.md"]
exclude = ["docs/excluded/**"]
"#,
        );
        project
    }

    fn root(&self) -> &Path {
        self.0.path()
    }

    fn write(&self, path: &str, contents: &str) {
        let path = self.root().join(path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, contents).unwrap();
    }

    fn read(&self, path: &str) -> String {
        fs::read_to_string(self.root().join(path)).unwrap()
    }
}

fn dispatcher() -> Dispatcher {
    let mut dispatcher = Dispatcher::new();
    dispatcher.register(".h.rs", RustHeader).unwrap();
    dispatcher
}

fn fence(out: &str, code: &str) -> String {
    format!("```rust out={out}\n{code}\n```\n")
}

struct Inspect {
    calls: Rc<Cell<usize>>,
}

impl Preprocessor for Inspect {
    fn preprocess(&self, blocks: Vec<TokenStream>, context: &Context) -> TokenStream {
        self.calls.set(self.calls.get() + 1);
        assert!(context.project_root.is_absolute());
        assert_eq!(context.out, Path::new("generated/combined.h.rs"));
        assert_eq!(
            blocks.iter().map(ToString::to_string).collect::<Vec<_>>(),
            ["pub struct", "First ;", "pub struct Second ;"]
        );
        assert_eq!(
            context
                .sources
                .iter()
                .map(|source| source.document.as_path())
                .collect::<Vec<_>>(),
            [
                Path::new("docs/a.md"),
                Path::new("docs/a.md"),
                Path::new("docs/z.md")
            ]
        );
        blocks.into_iter().collect()
    }
}

struct WrongSuffix;

impl Preprocessor for WrongSuffix {
    fn preprocess(&self, _: Vec<TokenStream>, _: &Context) -> TokenStream {
        panic!("a shorter suffix must not win");
    }
}

#[test]
fn groups_independent_streams_across_documents_and_injects_the_longest_suffix() {
    let project = Project::new();
    project.write("docs/a.md", &format!("{}{}\n```rust\nthis is an unmarked example {{\n```\n\n````markdown\n```rust out=ignored.h.rs\nnot processed\n```\n````\n", fence("generated/combined.h.rs", "pub struct"), fence("generated/combined.h.rs", "First;")));
    project.write(
        "docs/z.md",
        &fence("generated/combined.h.rs", "pub struct Second;"),
    );
    project.write("docs/excluded/bad.md", &fence("excluded.h.rs", "{"));
    let calls = Rc::new(Cell::new(0));
    let mut dispatcher = Dispatcher::new();
    dispatcher.register(".rs", WrongSuffix).unwrap();
    dispatcher
        .register(
            ".h.rs",
            Inspect {
                calls: Rc::clone(&calls),
            },
        )
        .unwrap();
    assert_eq!(
        dispatcher.generate(project.root()).unwrap(),
        [PathBuf::from("generated/combined.h.rs")]
    );
    assert_eq!(calls.get(), 1);
    let generated = project.read("generated/combined.h.rs");
    assert!(generated.starts_with(
        "// Generated by md-first. DO NOT EDIT.\n// Source: docs/a.md\n// Source: docs/z.md\n"
    ));
    let file = syn::parse_file(&generated).unwrap();
    assert_eq!(file.items.len(), 2);
    assert!(!project.root().join("ignored.h.rs").exists());
}

#[test]
fn failed_generation_preserves_outputs_and_success_replaces_them() {
    let project = Project::new();
    project.write("docs/a.md", &fence("generated/a.h.rs", "pub struct First;"));
    project.write(
        "docs/b.md",
        "> ```rust out=generated/b.h.rs\n> pub struct Broken {\n>     number: u64,\n> }\n> ```\n",
    );
    project.write("generated/a.h.rs", "handwritten contents");
    let dispatcher = dispatcher();
    let error = dispatcher.generate(project.root()).unwrap_err().to_string();
    assert!(
        error.contains("docs/b.md:3:7: struct fields must explicitly use pub"),
        "{error}"
    );
    assert_eq!(project.read("generated/a.h.rs"), "handwritten contents");
    assert!(!project.root().join("generated/b.h.rs").exists());

    project.write(
        "docs/b.md",
        &fence("generated/b.h.rs", "pub struct Second;"),
    );
    dispatcher.generate(project.root()).unwrap();
    dispatcher.check(project.root()).unwrap();
    assert!(
        project
            .read("generated/a.h.rs")
            .contains("pub struct First;")
    );
    project.write("generated/a.h.rs", "stale");
    let error = dispatcher.check(project.root()).unwrap_err().to_string();
    assert!(
        error.contains("generated/a.h.rs: generated output is stale"),
        "{error}"
    );
    assert_eq!(project.read("generated/a.h.rs"), "stale");
}

#[test]
fn reports_a_processors_diagnostic_in_the_original_unicode_container() {
    struct Reject;
    impl Preprocessor for Reject {
        fn preprocess(&self, blocks: Vec<TokenStream>, context: &Context) -> TokenStream {
            let token = blocks[1].clone().into_iter().last().unwrap();
            context.error(1, token.span(), "rejected token");
            TokenStream::new()
        }
    }
    let project = Project::new();
    project.write(
        "docs/a.md",
        &format!(
            "{}\n- item\n\n  ```rust out=generated/a.h.rs\n  \"中文\" rejected\n  ```\n",
            fence("generated/a.h.rs", "first")
        ),
    );
    let mut dispatcher = Dispatcher::new();
    dispatcher.register(".h.rs", Reject).unwrap();
    let error = dispatcher.generate(project.root()).unwrap_err().to_string();
    assert!(error.contains("docs/a.md:8:12: rejected token"), "{error}");
    assert!(!project.root().join("generated").exists());
}

#[test]
fn lexes_each_block_separately_even_when_the_combination_would_balance() {
    let project = Project::new();
    project.write(
        "docs/a.md",
        &(fence("generated/a.h.rs", "pub struct A {") + &fence("generated/a.h.rs", "}")),
    );
    let error = dispatcher()
        .generate(project.root())
        .unwrap_err()
        .to_string();
    assert!(error.contains("docs/a.md:"), "{error}");
    assert!(!project.root().join("generated").exists());
}

#[test]
fn rust_header_can_combine_partial_items_and_rejects_misplaced_markers() {
    let project = Project::new();
    project.write(
        "docs/a.md",
        &(fence("generated/a.h.rs", "pub struct") + &fence("generated/a.h.rs", "Combined;")),
    );
    let dispatcher = dispatcher();
    dispatcher.generate(project.root()).unwrap();
    assert!(
        project
            .read("generated/a.h.rs")
            .contains("pub struct Combined;")
    );
    project.write(
        "docs/b.md",
        &fence("generated/a.h.rs", "#[spec::header] pub struct Wrong;"),
    );
    let error = dispatcher.generate(project.root()).unwrap_err().to_string();
    assert!(
        error.contains("docs/b.md:2:1: unknown or misplaced spec attribute"),
        "{error}"
    );
}

#[test]
fn reports_unknown_suffixes_and_prevents_output_paths_leaving_the_project() {
    let project = Project::new();
    for (out, expected) in [
        ("generated/a.unknown", "no preprocessor registered"),
        ("../a.h.rs", "path escapes project root"),
    ] {
        project.write("docs/a.md", &fence(out, "pub struct A;"));
        let error = dispatcher()
            .generate(project.root())
            .unwrap_err()
            .to_string();
        assert!(error.contains(expected), "{error}");
    }
    assert!(!project.root().join("generated").exists());
}

#[cfg(unix)]
#[test]
fn output_symlinks_cannot_create_files_outside_the_project() {
    use std::os::unix::fs::symlink;

    let project = Project::new();
    let outside = tempfile::tempdir().unwrap();
    let external_target = outside.path().join("escaped.h.rs");
    project.write(
        "docs/a.md",
        &(fence("generated/a.h.rs", "pub struct First;")
            + &fence("generated/z.h.rs", "pub struct Second;")),
    );
    project.write("generated/a.h.rs", "keep existing output");
    let link = project.root().join("generated/z.h.rs");
    symlink(&external_target, &link).unwrap();

    let dispatcher = dispatcher();
    let error = dispatcher.generate(project.root()).unwrap_err().to_string();
    assert!(error.contains("generated/z.h.rs"), "{error}");
    assert_eq!(project.read("generated/a.h.rs"), "keep existing output");
    assert!(!external_target.exists());
    assert!(dispatcher.check(project.root()).is_err());
    assert!(!external_target.exists());

    fs::remove_file(&link).unwrap();
    project.write(
        "generated/actual.h.rs",
        "existing target inside the project",
    );
    symlink("actual.h.rs", &link).unwrap();
    dispatcher.generate(project.root()).unwrap();
    dispatcher.check(project.root()).unwrap();
    assert!(
        project
            .read("generated/actual.h.rs")
            .contains("pub struct Second;")
    );
}

#[test]
fn generated_header_compiles_and_calls_handwritten_implementations() {
    let project = Project::new();
    project.write(
        "docs/a.md",
        &fence(
            "generated/holder.h.rs",
            r#"
#[spec::private_fields]
pub struct Holder<'a, T, const N: usize> {
    pub name: &'a str,
}

#[spec::header]
impl<'a, T: Copy, const N: usize> Holder<'a, T, N> {
    /// Construct a holder without copying its input array.
    pub fn new(name: &'a str, values: &'a [T; N]) -> Self;
    pub fn get(&self, index: usize) -> T;
    pub const fn capacity() -> usize;
    pub fn boxed(self: Box<Self>) -> T;
    pub fn choose<U: Default, const M: usize>() -> (U, usize);
    pub fn unpack((a, b): (usize, usize), r#__md_first_argument_0: usize) -> usize;
    pub fn borrowed(ref value: String, __md_first_argument_0: usize) -> usize;
    pub fn ignored(_: usize, __md_first_argument_0: usize) -> usize;
    #[allow(non_upper_case_globals)]
    pub fn constant<const __md_first_argument_0: usize>(_: usize) -> usize;
    pub fn conditional(#[cfg(any())] unused: usize, value: usize) -> usize;
    pub unsafe fn read(pointer: *const T) -> T;
    pub async fn first(&self) -> T;
}

#[repr(C)]
pub union Bits { pub number: u64, pub bytes: [u8; 8] }

pub trait Value { fn value(&self) -> u32; }
impl Value for u32 { fn value(&self) -> u32 { *self } }
macro_rules! identity { ($value:expr) => { $value }; }
"#,
        ),
    );
    dispatcher().generate(project.root()).unwrap();
    project.write("main.rs", r#"
use std::future::Future;
use std::task::{Context, Poll, Waker};
include!("generated/holder.h.rs");

struct HolderInner<'a, T, const N: usize> { values: &'a [T; N] }
impl<'a, T: Copy, const N: usize> Holder<'a, T, N> {
    fn new_impl(name: &'a str, values: &'a [T; N]) -> Self { Self { name, inner: HolderInner { values } } }
    fn get_impl(&self, index: usize) -> T { self.inner.values[index] }
    const fn capacity_impl() -> usize { N }
    fn boxed_impl(self: Box<Self>) -> T { self.get(0) }
    fn choose_impl<U: Default, const M: usize>() -> (U, usize) { (U::default(), M) }
    fn unpack_impl((a, b): (usize, usize), extra: usize) -> usize { a + b + extra }
    fn borrowed_impl(value: String, extra: usize) -> usize { value.len() + extra }
    fn ignored_impl(value: usize, extra: usize) -> usize { value + extra }
    #[allow(non_upper_case_globals)]
    fn constant_impl<const __md_first_argument_0: usize>(value: usize) -> usize { value + __md_first_argument_0 }
    fn conditional_impl(#[cfg(any())] unused: usize, value: usize) -> usize { value }
    unsafe fn read_impl(pointer: *const T) -> T { unsafe { *pointer } }
    async fn first_impl(&self) -> T { self.get(0) }
}

fn main() {
    let values = [11, 22];
    let holder = Holder::new("sample", &values);
    assert_eq!(holder.get(1), 22);
    assert_eq!(Holder::<u32, 2>::capacity(), 2);
    assert_eq!(Holder::<u32, 2>::choose::<String, 7>(), (String::new(), 7));
    assert_eq!(Holder::<u32, 2>::unpack((3, 4), 9), 16);
    assert_eq!(Holder::<u32, 2>::borrowed("abcd".into(), 9), 13);
    assert_eq!(Holder::<u32, 2>::ignored(3, 9), 12);
    assert_eq!(Holder::<u32, 2>::constant::<7>(3), 10);
    assert_eq!(Holder::<u32, 2>::conditional(9), 9);
    assert_eq!(unsafe { Holder::<u32, 2>::read(values.as_ptr()) }, 11);
    let mut future = std::pin::pin!(holder.first());
    assert_eq!(future.as_mut().poll(&mut Context::from_waker(Waker::noop())), Poll::Ready(11));
    assert_eq!(Box::new(Holder::new("boxed", &values)).boxed(), 11);
    assert_eq!(identity!(11_u32.value()), 11);
}
"#);
    let binary = project.root().join("consumer");
    let result = Command::new("rustc")
        .args(["--edition=2024", "--deny=warnings"])
        .arg(project.root().join("main.rs"))
        .arg("-o")
        .arg(&binary)
        .output()
        .unwrap();
    assert!(
        result.status.success(),
        "{}",
        String::from_utf8_lossy(&result.stderr)
    );
    assert!(Command::new(binary).status().unwrap().success());
}

#[test]
fn cli_uses_the_selected_project_root_and_check_never_writes() {
    let project = Project::new();
    project.write("docs/a.md", &fence("generated/a.h.rs", "pub struct A;"));
    let run = |check| {
        let mut command = Command::new(env!("CARGO_BIN_EXE_md-first"));
        command.current_dir(project.root().join("docs"));
        if check {
            command.arg("--check");
        }
        command.arg(project.root()).output().unwrap()
    };
    let missing = run(true);
    assert!(!missing.status.success());
    assert!(!project.root().join("generated").exists());
    let generated = run(false);
    assert!(
        generated.status.success(),
        "{}",
        String::from_utf8_lossy(&generated.stderr)
    );
    assert!(run(true).status.success());
}

#[test]
fn own_specs_reproduce_the_interface_used_to_compile_this_test() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    dispatcher().check(root).unwrap();
}
