use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::{Error, markdown::valid_key};

pub(crate) const GENERATED_MARKER: &str = "// Generated by spec-codegen. Do not edit.\n";
const MANIFEST: &str = ".spec-codegen-manifest";
const MANIFEST_VERSION: &str = "spec-codegen-v1";

pub(crate) fn write(
    directory: &Path,
    headers: &BTreeMap<String, String>,
) -> Result<Vec<PathBuf>, Error> {
    fs::create_dir_all(directory).map_err(|error| Error::io(directory, error))?;
    let manifest = directory.join(MANIFEST);
    let old = read_manifest(&manifest)?;
    let current: BTreeSet<_> = headers.keys().map(|key| format!("{key}.h.rs")).collect();
    let owned: BTreeSet<_> = old.union(&current).cloned().collect();

    // Validate every destination before replacing any file. Never follow output
    // symlinks or adopt existing handwritten files, even in an otherwise shared OUT_DIR.
    for name in &owned {
        let path = directory.join(name);
        if let Some(contents) = read_regular(&path)?
            && (!old.contains(name) || !contents.starts_with(GENERATED_MARKER))
        {
            return Err(Error::new(format!(
                "{}: refusing to replace a file not owned by spec-codegen",
                path.display()
            )));
        }
    }

    // Record the union first: an interrupted write leaves every possibly created
    // header tracked, so a later successful invocation can safely reconcile it.
    write_manifest(&manifest, &owned)?;
    for (key, contents) in headers {
        replace(&directory.join(format!("{key}.h.rs")), contents)?;
    }
    for name in old.difference(&current) {
        let path = directory.join(name);
        match fs::remove_file(&path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(Error::io(&path, error)),
        }
    }
    write_manifest(&manifest, &current)?;
    Ok(current
        .into_iter()
        .map(|name| directory.join(name))
        .collect())
}

fn read_regular(path: &Path) -> Result<Option<String>, Error> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if !metadata.file_type().is_file() => Err(Error::new(format!(
            "{}: expected a regular file, not a symlink or directory",
            path.display()
        ))),
        Ok(_) => fs::read_to_string(path)
            .map(Some)
            .map_err(|error| Error::io(path, error)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(Error::io(path, error)),
    }
}

fn read_manifest(path: &Path) -> Result<BTreeSet<String>, Error> {
    let Some(text) = read_regular(path)? else {
        return Ok(BTreeSet::new());
    };
    let mut lines = text.lines();
    if lines.next() != Some(MANIFEST_VERSION) {
        return Err(Error::new(format!(
            "{}: invalid ownership manifest",
            path.display()
        )));
    }
    let mut names = BTreeSet::new();
    for name in lines {
        if !name.strip_suffix(".h.rs").is_some_and(valid_key) || !names.insert(name.to_owned()) {
            return Err(Error::new(format!(
                "{}: invalid header filename in ownership manifest",
                path.display()
            )));
        }
    }
    Ok(names)
}

fn write_manifest(path: &Path, names: &BTreeSet<String>) -> Result<(), Error> {
    let mut contents = format!("{MANIFEST_VERSION}\n");
    for name in names {
        contents.push_str(name);
        contents.push('\n');
    }
    replace(path, &contents)
}

fn replace(path: &Path, contents: &str) -> Result<(), Error> {
    if read_regular(path)?.as_deref() == Some(contents) {
        return Ok(());
    }
    let directory = path.parent().expect("output files have a parent");
    let mut staging =
        tempfile::NamedTempFile::new_in(directory).map_err(|error| Error::io(directory, error))?;
    staging
        .write_all(contents.as_bytes())
        .map_err(|error| Error::io(path, error))?;
    staging
        .persist(path)
        .map_err(|error| Error::io(path, error.error))?;
    Ok(())
}
