use crate::semantic::{FunctionCategory, FunctionSig, ParamSig, Ty};

pub fn builtins_functions() -> Vec<FunctionSig> {
    vec![
        // =========================
        // General / Logic
        // =========================
        FunctionSig {
            name: "if".into(),
            params: vec![
                ParamSig {
                    name: Some("condition".into()),
                    ty: Ty::Boolean,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("then".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("else".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Unknown,
            detail: Some("if(condition, then, else)".into()),
            min_args: 0,
            category: FunctionCategory::General,
        },
        FunctionSig {
            name: "ifs".into(),
            // Note: Notion's ifs is (cond1, value1, cond2, value2, ..., default)
            // ParamSig can't express pair-groups well; we model as variadic values.
            params: vec![ParamSig {
                name: Some("args".into()),
                ty: Ty::Unknown,
                optional: false,
                variadic: true,
            }],
            ret: Ty::Unknown,
            detail: Some("ifs(condition, value, ..., default)".into()),
            min_args: 3,
            category: FunctionCategory::General,
        },
        FunctionSig {
            name: "empty".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Boolean,
            detail: Some("empty(value)".into()),
            min_args: 1,
            category: FunctionCategory::General,
        },
        FunctionSig {
            name: "format".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }],
            ret: Ty::String,
            detail: Some("format(value)".into()),
            min_args: 1,
            category: FunctionCategory::General,
        },
        FunctionSig {
            name: "toNumber".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("toNumber(value)".into()),
            min_args: 1,
            category: FunctionCategory::General,
        },
        // =========================
        // Text
        // =========================
        FunctionSig {
            name: "length".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Union(vec![Ty::String, Ty::List(Box::new(Ty::Unknown))]),
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("length(text|any[])".into()),
            min_args: 1,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "substring".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("start".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("end".into()),
                    ty: Ty::Number,
                    optional: true,
                    variadic: false,
                },
            ],
            ret: Ty::String,
            detail: Some("substring(text, start, end?)".into()),
            min_args: 2,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "contains".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("search".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Boolean,
            detail: Some("contains(text, search)".into()),
            min_args: 2,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "test".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("regex".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Boolean,
            detail: Some("test(text, regex)".into()),
            min_args: 2,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "match".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("regex".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::List(Box::new(Ty::String)),
            detail: Some("match(text, regex)".into()),
            min_args: 2,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "replace".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("regex".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("replacement".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::String,
            detail: Some("replace(text, regex, replacement)".into()),
            min_args: 3,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "replaceAll".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("regex".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("replacement".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::String,
            detail: Some("replaceAll(text, regex, replacement)".into()),
            min_args: 3,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "lower".into(),
            params: vec![ParamSig {
                name: Some("text".into()),
                ty: Ty::String,
                optional: false,
                variadic: false,
            }],
            ret: Ty::String,
            detail: Some("lower(text)".into()),
            min_args: 1,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "upper".into(),
            params: vec![ParamSig {
                name: Some("text".into()),
                ty: Ty::String,
                optional: false,
                variadic: false,
            }],
            ret: Ty::String,
            detail: Some("upper(text)".into()),
            min_args: 1,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "repeat".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("times".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::String,
            detail: Some("repeat(text, times)".into()),
            min_args: 2,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "link".into(),
            params: vec![
                ParamSig {
                    name: Some("label".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("url".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::String,
            detail: Some("link(label, url)".into()),
            min_args: 2,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "style".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("styles".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: true,
                },
            ],
            ret: Ty::String,
            detail: Some("style(text, styleOrColor, ...)".into()),
            min_args: 2,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "unstyle".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("styles".into()),
                    ty: Ty::String,
                    optional: true,
                    variadic: true,
                },
            ],
            ret: Ty::String,
            detail: Some("unstyle(text, style?)".into()),
            min_args: 1,
            category: FunctionCategory::Text,
        },
        FunctionSig {
            name: "trim".into(),
            params: vec![ParamSig {
                name: Some("text".into()),
                ty: Ty::String,
                optional: false,
                variadic: false,
            }],
            ret: Ty::String,
            detail: Some("trim(text)".into()),
            min_args: 1,
            category: FunctionCategory::Text,
        },
        // =========================
        // Number
        // =========================
        FunctionSig {
            name: "add".into(),
            params: vec![
                ParamSig {
                    name: Some("a".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("b".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("add(a, b)".into()),
            min_args: 2,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "subtract".into(),
            params: vec![
                ParamSig {
                    name: Some("a".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("b".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("subtract(a, b)".into()),
            min_args: 2,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "multiply".into(),
            params: vec![
                ParamSig {
                    name: Some("a".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("b".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("multiply(a, b)".into()),
            min_args: 2,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "divide".into(),
            params: vec![
                ParamSig {
                    name: Some("a".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("b".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("divide(a, b)".into()),
            min_args: 2,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "mod".into(),
            params: vec![
                ParamSig {
                    name: Some("a".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("b".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("mod(a, b)".into()),
            min_args: 2,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "pow".into(),
            params: vec![
                ParamSig {
                    name: Some("base".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("exp".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("pow(base, exp)".into()),
            min_args: 2,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "min".into(),
            params: vec![ParamSig {
                name: Some("values".into()),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }],
            ret: Ty::Number,
            detail: Some("min(number|number[], ...)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "max".into(),
            params: vec![ParamSig {
                name: Some("values".into()),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }],
            ret: Ty::Number,
            detail: Some("max(number|number[], ...)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "sum".into(),
            params: vec![ParamSig {
                name: Some("values".into()),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }],
            ret: Ty::Number,
            detail: Some("sum(number|number[], ...)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "median".into(),
            params: vec![ParamSig {
                name: Some("values".into()),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }],
            ret: Ty::Number,
            detail: Some("median(number|number[], ...)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "mean".into(),
            params: vec![ParamSig {
                name: Some("values".into()),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }],
            ret: Ty::Number,
            detail: Some("mean(number|number[], ...)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "abs".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("abs(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "round".into(),
            params: vec![
                ParamSig {
                    name: Some("value".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("places".into()),
                    ty: Ty::Number,
                    optional: true,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("round(number, places?)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "ceil".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("ceil(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "floor".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("floor(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "sqrt".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("sqrt(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "cbrt".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("cbrt(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "exp".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("exp(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "ln".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("ln(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "log10".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("log10(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "log2".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("log2(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "sign".into(),
            params: vec![ParamSig {
                name: Some("value".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("sign(number)".into()),
            min_args: 1,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "pi".into(),
            params: vec![],
            ret: Ty::Number,
            detail: Some("pi()".into()),
            min_args: 0,
            category: FunctionCategory::Number,
        },
        FunctionSig {
            name: "e".into(),
            params: vec![],
            ret: Ty::Number,
            detail: Some("e()".into()),
            min_args: 0,
            category: FunctionCategory::Number,
        },
        // =========================
        // Date
        // =========================
        FunctionSig {
            name: "now".into(),
            params: vec![],
            ret: Ty::Date,
            detail: Some("now()".into()),
            min_args: 0,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "today".into(),
            params: vec![],
            ret: Ty::Date,
            detail: Some("today()".into()),
            min_args: 0,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "minute".into(),
            params: vec![ParamSig {
                name: Some("date".into()),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("minute(date)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "hour".into(),
            params: vec![ParamSig {
                name: Some("date".into()),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("hour(date)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "day".into(),
            params: vec![ParamSig {
                name: Some("date".into()),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("day(date)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "date".into(),
            params: vec![ParamSig {
                name: Some("date".into()),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("date(date)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "week".into(),
            params: vec![ParamSig {
                name: Some("date".into()),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("week(date)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "month".into(),
            params: vec![ParamSig {
                name: Some("date".into()),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("month(date)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "year".into(),
            params: vec![ParamSig {
                name: Some("date".into()),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("year(date)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "dateAdd".into(),
            params: vec![
                ParamSig {
                    name: Some("date".into()),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("amount".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("unit".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Date,
            detail: Some("dateAdd(date, amount, unit)".into()),
            min_args: 3,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "dateSubtract".into(),
            params: vec![
                ParamSig {
                    name: Some("date".into()),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("amount".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("unit".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Date,
            detail: Some("dateSubtract(date, amount, unit)".into()),
            min_args: 3,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "dateBetween".into(),
            params: vec![
                ParamSig {
                    name: Some("a".into()),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("b".into()),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("unit".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("dateBetween(a, b, unit)".into()),
            min_args: 3,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "dateRange".into(),
            params: vec![
                ParamSig {
                    name: Some("start".into()),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("end".into()),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
            ],
            // Note: if you have Ty::DateRange, use it instead of Ty::Date here.
            ret: Ty::Date,
            detail: Some("dateRange(start, end)".into()),
            min_args: 2,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "dateStart".into(),
            params: vec![ParamSig {
                name: Some("range".into()),
                // Note: if you have Ty::DateRange, use it here instead of Ty::Date.
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Date,
            detail: Some("dateStart(range)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "dateEnd".into(),
            params: vec![ParamSig {
                name: Some("range".into()),
                // Note: if you have Ty::DateRange, use it here instead of Ty::Date.
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Date,
            detail: Some("dateEnd(range)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "timestamp".into(),
            params: vec![ParamSig {
                name: Some("date".into()),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Number,
            detail: Some("timestamp(date)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "fromTimestamp".into(),
            params: vec![ParamSig {
                name: Some("timestamp".into()),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Date,
            detail: Some("fromTimestamp(timestampMs)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "formatDate".into(),
            params: vec![
                ParamSig {
                    name: Some("date".into()),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("format".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::String,
            detail: Some("formatDate(date, format)".into()),
            min_args: 2,
            category: FunctionCategory::Date,
        },
        FunctionSig {
            name: "parseDate".into(),
            params: vec![ParamSig {
                name: Some("text".into()),
                ty: Ty::String,
                optional: false,
                variadic: false,
            }],
            ret: Ty::Date,
            detail: Some("parseDate(text)".into()),
            min_args: 1,
            category: FunctionCategory::Date,
        },
        // =========================
        // People
        // =========================
        FunctionSig {
            name: "name".into(),
            params: vec![ParamSig {
                name: Some("person".into()),
                // TODO: Notion's person type is more complex than this.
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }],
            ret: Ty::String,
            detail: Some("name(person)".into()),
            min_args: 1,
            category: FunctionCategory::People,
        },
        FunctionSig {
            name: "email".into(),
            params: vec![ParamSig {
                name: Some("person".into()),
                // TODO: Notion's person type is more complex than this.
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }],
            ret: Ty::String,
            detail: Some("email(person)".into()),
            min_args: 1,
            category: FunctionCategory::People,
        },
        // =========================
        // List
        // =========================
        FunctionSig {
            name: "at".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("index".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Unknown,
            detail: Some("at(list, index)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "first".into(),
            params: vec![ParamSig {
                name: Some("list".into()),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }],
            ret: Ty::Unknown,
            detail: Some("first(list)".into()),
            min_args: 1,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "last".into(),
            params: vec![ParamSig {
                name: Some("list".into()),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }],
            ret: Ty::Unknown,
            detail: Some("last(list)".into()),
            min_args: 1,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "slice".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("start".into()),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("end".into()),
                    ty: Ty::Number,
                    optional: true,
                    variadic: false,
                },
            ],
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("slice(list, start, end?)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "concat".into(),
            params: vec![ParamSig {
                name: Some("lists".into()),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: true,
            }],
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("concat(list, ...)".into()),
            min_args: 1,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "sort".into(),
            params: vec![ParamSig {
                name: Some("list".into()),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }],
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("sort(list)".into()),
            min_args: 1,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "reverse".into(),
            params: vec![ParamSig {
                name: Some("list".into()),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }],
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("reverse(list)".into()),
            min_args: 1,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "join".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("separator".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::String,
            detail: Some("join(list, separator)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "split".into(),
            params: vec![
                ParamSig {
                    name: Some("text".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("separator".into()),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::List(Box::new(Ty::String)),
            detail: Some("split(text, separator)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "unique".into(),
            params: vec![ParamSig {
                name: Some("list".into()),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }],
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("unique(list)".into()),
            min_args: 1,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "includes".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("value".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Boolean,
            detail: Some("includes(list, value)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "find".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("predicate".into()),
                    ty: Ty::Unknown, // lambda expr (current/index) in Notion DSL
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Unknown,
            detail: Some("find(list, predicate)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "findIndex".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("predicate".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Number,
            detail: Some("findIndex(list, predicate)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "filter".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("predicate".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("filter(list, predicate)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "some".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("predicate".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Boolean,
            detail: Some("some(list, predicate)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "every".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("predicate".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Boolean,
            detail: Some("every(list, predicate)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "map".into(),
            params: vec![
                ParamSig {
                    name: Some("list".into()),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("mapper".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("map(list, mapper)".into()),
            min_args: 2,
            category: FunctionCategory::List,
        },
        FunctionSig {
            name: "flat".into(),
            params: vec![ParamSig {
                name: Some("list".into()),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }],
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("flat(list)".into()),
            min_args: 1,
            category: FunctionCategory::List,
        },
        // =========================
        // Special / Utility
        // =========================
        FunctionSig {
            name: "id".into(),
            params: vec![ParamSig {
                name: Some("page".into()),
                ty: Ty::Unknown, // if you have Ty::Page, use it here
                optional: true,
                variadic: false,
            }],
            ret: Ty::String,
            detail: Some("id(page?)".into()),
            min_args: 0,
            category: FunctionCategory::Special,
        },
        FunctionSig {
            name: "equal".into(),
            params: vec![
                ParamSig {
                    name: Some("a".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("b".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Boolean,
            detail: Some("equal(a, b)".into()),
            min_args: 2,
            category: FunctionCategory::Special,
        },
        FunctionSig {
            name: "unequal".into(),
            params: vec![
                ParamSig {
                    name: Some("a".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("b".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Boolean,
            detail: Some("unequal(a, b)".into()),
            min_args: 2,
            category: FunctionCategory::Special,
        },
        FunctionSig {
            name: "let".into(),
            // let(var, value, expr)
            params: vec![
                ParamSig {
                    name: Some("var".into()),
                    ty: Ty::Unknown, // identifier slot
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("value".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: Some("expr".into()),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ],
            ret: Ty::Unknown,
            detail: Some("let(var, value, expr)".into()),
            min_args: 3,
            category: FunctionCategory::Special,
        },
        FunctionSig {
            name: "lets".into(),
            // lets(a, v1, b, v2, ..., expr)
            params: vec![ParamSig {
                name: Some("args".into()),
                ty: Ty::Unknown,
                optional: false,
                variadic: true,
            }],
            ret: Ty::Unknown,
            detail: Some("lets(var1, value1, ..., expr)".into()),
            min_args: 3,
            category: FunctionCategory::Special,
        },
    ]
}
