use super::{
    FunctionCategory, FunctionSig, GenericId, GenericParam, GenericParamKind, ParamLayout, ParamSig,
    Ty,
};

pub fn builtins_functions() -> Vec<FunctionSig> {
    let t0 = GenericId(0);
    let builtins = vec![
        // =========================
        // General / Logic
        // =========================
        FunctionSig {
            name: "if".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "condition".into(),
                    ty: Ty::Boolean,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "then".into(),
                    ty: Ty::Generic(t0),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "else".into(),
                    ty: Ty::Generic(t0),
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Generic(t0),
            detail: Some("if(condition, then, else)".into()),
            category: FunctionCategory::General,
            generics: vec![GenericParam {
                id: t0,
                name: "T".into(),
                kind: GenericParamKind::Plain,
            }],
        },
        FunctionSig {
            name: "ifs".into(),
            layout: ParamLayout::RepeatGroup {
                head: vec![],
                repeat: vec![
                    ParamSig {
                        name: "condition".into(),
                        ty: Ty::Boolean,
                        optional: false,
                        variadic: false,
                    },
                    ParamSig {
                        name: "value".into(),
                        ty: Ty::Generic(t0),
                        optional: false,
                        variadic: false,
                    },
                ],
                tail: vec![ParamSig {
                    name: "default".into(),
                    ty: Ty::Generic(t0),
                    optional: false,
                    variadic: false,
                }],
            },
            ret: Ty::Generic(t0),
            detail: Some("ifs(condition, value, ..., default)".into()),
            category: FunctionCategory::General,
            generics: vec![GenericParam {
                id: t0,
                name: "T".into(),
                kind: GenericParamKind::Variant,
            }],
        },
        FunctionSig {
            name: "empty".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Boolean,
            detail: Some("empty(value)".into()),
            category: FunctionCategory::General,
            generics: vec![],
        },
        FunctionSig {
            name: "format".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::String,
            detail: Some("format(value)".into()),
            category: FunctionCategory::General,
            generics: vec![],
        },
        FunctionSig {
            name: "toNumber".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("toNumber(value)".into()),
            category: FunctionCategory::General,
            generics: vec![],
        },
        // =========================
        // Text
        // =========================
        FunctionSig {
            name: "length".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Union(vec![Ty::String, Ty::List(Box::new(Ty::Unknown))]),
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("length(text|any[])".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "substring".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "start".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "end".into(),
                    ty: Ty::Number,
                    optional: true,
                    variadic: false,
                },
            ]),
            ret: Ty::String,
            detail: Some("substring(text, start, end?)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "contains".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "search".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Boolean,
            detail: Some("contains(text, search)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "test".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "regex".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Boolean,
            detail: Some("test(text, regex)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "match".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "regex".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::List(Box::new(Ty::String)),
            detail: Some("match(text, regex)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "replace".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "regex".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "replacement".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::String,
            detail: Some("replace(text, regex, replacement)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "replaceAll".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "regex".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "replacement".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::String,
            detail: Some("replaceAll(text, regex, replacement)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "lower".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "text".into(),
                ty: Ty::String,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::String,
            detail: Some("lower(text)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "upper".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "text".into(),
                ty: Ty::String,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::String,
            detail: Some("upper(text)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "repeat".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "times".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::String,
            detail: Some("repeat(text, times)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "link".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "label".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "url".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::String,
            detail: Some("link(label, url)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "style".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "styles".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: true,
                },
            ]),
            ret: Ty::String,
            detail: Some("style(text, styleOrColor, ...)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "unstyle".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "styles".into(),
                    ty: Ty::String,
                    optional: true,
                    variadic: true,
                },
            ]),
            ret: Ty::String,
            detail: Some("unstyle(text, style?)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        FunctionSig {
            name: "trim".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "text".into(),
                ty: Ty::String,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::String,
            detail: Some("trim(text)".into()),
            category: FunctionCategory::Text,
            generics: vec![],
        },
        // =========================
        // Number
        // =========================
        FunctionSig {
            name: "add".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "a".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "b".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("add(a, b)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "subtract".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "a".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "b".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("subtract(a, b)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "multiply".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "a".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "b".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("multiply(a, b)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "divide".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "a".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "b".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("divide(a, b)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "mod".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "a".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "b".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("mod(a, b)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "pow".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "base".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "exp".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("pow(base, exp)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "min".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "values".into(),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }]),
            ret: Ty::Number,
            detail: Some("min(number|number[], ...)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "max".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "values".into(),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }]),
            ret: Ty::Number,
            detail: Some("max(number|number[], ...)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "sum".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "values".into(),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }]),
            ret: Ty::Number,
            detail: Some("sum(number|number[], ...)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "median".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "values".into(),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }]),
            ret: Ty::Number,
            detail: Some("median(number|number[], ...)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "mean".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "values".into(),
                ty: Ty::Union(vec![Ty::Number, Ty::List(Box::new(Ty::Number))]),
                optional: false,
                variadic: true,
            }]),
            ret: Ty::Number,
            detail: Some("mean(number|number[], ...)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "abs".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("abs(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "round".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "value".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "places".into(),
                    ty: Ty::Number,
                    optional: true,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("round(number, places?)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "ceil".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("ceil(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "floor".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("floor(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "sqrt".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("sqrt(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "cbrt".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("cbrt(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "exp".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("exp(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "ln".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("ln(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "log10".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("log10(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "log2".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("log2(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "sign".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "value".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("sign(number)".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "pi".into(),
            layout: ParamLayout::Flat(vec![]),
            ret: Ty::Number,
            detail: Some("pi()".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        FunctionSig {
            name: "e".into(),
            layout: ParamLayout::Flat(vec![]),
            ret: Ty::Number,
            detail: Some("e()".into()),
            category: FunctionCategory::Number,
            generics: vec![],
        },
        // =========================
        // Date
        // =========================
        FunctionSig {
            name: "now".into(),
            layout: ParamLayout::Flat(vec![]),
            ret: Ty::Date,
            detail: Some("now()".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "today".into(),
            layout: ParamLayout::Flat(vec![]),
            ret: Ty::Date,
            detail: Some("today()".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "minute".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "date".into(),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("minute(date)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "hour".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "date".into(),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("hour(date)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "day".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "date".into(),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("day(date)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "date".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "date".into(),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("date(date)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "week".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "date".into(),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("week(date)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "month".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "date".into(),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("month(date)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "year".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "date".into(),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("year(date)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "dateAdd".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "date".into(),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "amount".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "unit".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Date,
            detail: Some("dateAdd(date, amount, unit)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "dateSubtract".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "date".into(),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "amount".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "unit".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Date,
            detail: Some("dateSubtract(date, amount, unit)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "dateBetween".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "a".into(),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "b".into(),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "unit".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("dateBetween(a, b, unit)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "dateRange".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "start".into(),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "end".into(),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
            ]),
            // Note: if you have Ty::DateRange, use it instead of Ty::Date here.
            ret: Ty::Date,
            detail: Some("dateRange(start, end)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "dateStart".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "range".into(),
                // Note: if you have Ty::DateRange, use it here instead of Ty::Date.
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Date,
            detail: Some("dateStart(range)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "dateEnd".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "range".into(),
                // Note: if you have Ty::DateRange, use it here instead of Ty::Date.
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Date,
            detail: Some("dateEnd(range)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "timestamp".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "date".into(),
                ty: Ty::Date,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Number,
            detail: Some("timestamp(date)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "fromTimestamp".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "timestamp".into(),
                ty: Ty::Number,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Date,
            detail: Some("fromTimestamp(timestampMs)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "formatDate".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "date".into(),
                    ty: Ty::Date,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "format".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::String,
            detail: Some("formatDate(date, format)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        FunctionSig {
            name: "parseDate".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "text".into(),
                ty: Ty::String,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Date,
            detail: Some("parseDate(text)".into()),
            category: FunctionCategory::Date,
            generics: vec![],
        },
        // =========================
        // People
        // =========================
        FunctionSig {
            name: "name".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "person".into(),
                // TODO: Notion's person type is more complex than this.
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::String,
            detail: Some("name(person)".into()),
            category: FunctionCategory::People,
            generics: vec![],
        },
        FunctionSig {
            name: "email".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "person".into(),
                // TODO: Notion's person type is more complex than this.
                ty: Ty::Unknown,
                optional: false,
                variadic: false,
            }]),
            ret: Ty::String,
            detail: Some("email(person)".into()),
            category: FunctionCategory::People,
            generics: vec![],
        },
        // =========================
        // List
        // =========================
        FunctionSig {
            name: "at".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "index".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Unknown,
            detail: Some("at(list, index)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "first".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "list".into(),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Unknown,
            detail: Some("first(list)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "last".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "list".into(),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }]),
            ret: Ty::Unknown,
            detail: Some("last(list)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "slice".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "start".into(),
                    ty: Ty::Number,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "end".into(),
                    ty: Ty::Number,
                    optional: true,
                    variadic: false,
                },
            ]),
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("slice(list, start, end?)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "concat".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "lists".into(),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: true,
            }]),
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("concat(list, ...)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "sort".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "list".into(),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }]),
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("sort(list)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "reverse".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "list".into(),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }]),
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("reverse(list)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "join".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "separator".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::String,
            detail: Some("join(list, separator)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "split".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "text".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "separator".into(),
                    ty: Ty::String,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::List(Box::new(Ty::String)),
            detail: Some("split(text, separator)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "unique".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "list".into(),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }]),
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("unique(list)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "includes".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "value".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Boolean,
            detail: Some("includes(list, value)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "find".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "predicate".into(),
                    ty: Ty::Unknown, // lambda expr (current/index) in Notion DSL
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Unknown,
            detail: Some("find(list, predicate)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "findIndex".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "predicate".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Number,
            detail: Some("findIndex(list, predicate)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "filter".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "predicate".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("filter(list, predicate)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "some".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "predicate".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Boolean,
            detail: Some("some(list, predicate)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "every".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "predicate".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Boolean,
            detail: Some("every(list, predicate)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "map".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "list".into(),
                    ty: Ty::List(Box::new(Ty::Unknown)),
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "mapper".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("map(list, mapper)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        FunctionSig {
            name: "flat".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "list".into(),
                ty: Ty::List(Box::new(Ty::Unknown)),
                optional: false,
                variadic: false,
            }]),
            ret: Ty::List(Box::new(Ty::Unknown)),
            detail: Some("flat(list)".into()),
            category: FunctionCategory::List,
            generics: vec![],
        },
        // =========================
        // Special / Utility
        // =========================
        FunctionSig {
            name: "id".into(),
            layout: ParamLayout::Flat(vec![ParamSig {
                name: "page".into(),
                ty: Ty::Unknown, // if you have Ty::Page, use it here
                optional: true,
                variadic: false,
            }]),
            ret: Ty::String,
            detail: Some("id(page?)".into()),
            category: FunctionCategory::Special,
            generics: vec![],
        },
        FunctionSig {
            name: "equal".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "a".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "b".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Boolean,
            detail: Some("equal(a, b)".into()),
            category: FunctionCategory::Special,
            generics: vec![],
        },
        FunctionSig {
            name: "unequal".into(),
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "a".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "b".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Boolean,
            detail: Some("unequal(a, b)".into()),
            category: FunctionCategory::Special,
            generics: vec![],
        },
        FunctionSig {
            name: "let".into(),
            // let(var, value, expr)
            layout: ParamLayout::Flat(vec![
                ParamSig {
                    name: "var".into(),
                    ty: Ty::Unknown, // identifier slot
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "value".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
                ParamSig {
                    name: "expr".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                },
            ]),
            ret: Ty::Unknown,
            detail: Some("let(var, value, expr)".into()),
            category: FunctionCategory::Special,
            generics: vec![],
        },
        FunctionSig {
            name: "lets".into(),
            // lets(a, v1, b, v2, ..., expr)
            layout: ParamLayout::RepeatGroup {
                head: vec![],
                repeat: vec![
                    ParamSig {
                        name: "var".into(),
                        ty: Ty::Unknown, // identifier slot
                        optional: false,
                        variadic: false,
                    },
                    ParamSig {
                        name: "value".into(),
                        ty: Ty::Unknown,
                        optional: false,
                        variadic: false,
                    },
                ],
                tail: vec![ParamSig {
                    name: "expr".into(),
                    ty: Ty::Unknown,
                    optional: false,
                    variadic: false,
                }],
            },
            ret: Ty::Unknown,
            detail: Some("lets(var1, value1, ..., expr)".into()),
            category: FunctionCategory::Special,
            generics: vec![],
        },
    ];
    builtins
}
