// Generated by md-first. DO NOT EDIT.
// Source: docs/specs/formula-engine.md

/// Date metadata shared by Evaluator and Engine; timestamps are UTC Unix milliseconds.
/// A missing end denotes a single date. Endpoints are preserved, including reversed ranges.
/// include_time controls format() display and dateBetween's midnight normalization, not stored timestamps.
/// Like legacy Date, unrestricted i64 endpoints pass Input validation; date operations check their range.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct DateValue {
    pub start: i64,
    pub end: Option<i64>,
    pub include_time: bool,
}
