// Generated by md-first. DO NOT EDIT.
// Source: docs/specs/wasm-api.md

use std::collections::HashMap;
use serde::{Deserialize, Serialize};
use ts_rs::TS;
pub use super::v1::{CompletionItem, SignatureItem, Span, TextEdit, Token};
pub type PropertyId = String;
pub type RowId = String;
pub type DraftVersion = u64;
pub type DiagnosticId = String;
pub type TextOffset = u32;
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub enum ValueType {
    Number,
    String,
    Boolean,
    Date,
    Unknown,
    List(Box<ValueType>),
    Union(Vec<ValueType>),
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields)]
pub struct FormulaSchema {
    pub properties: Vec<PropertyDefinition>,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub enum PropertyDefinition {
    Input { id: PropertyId, ty: ValueType },
    Formula(FormulaDefinition),
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields)]
pub struct FormulaDefinition {
    pub id: PropertyId,
    pub expression: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub enum FormulaEngineState {
    AllReady,
    NotAllReady { cycle_path: Vec<PropertyId> },
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub enum PropertyState {
    Input { id: PropertyId, ty: ValueType },
    Formula(FormulaState),
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct FormulaState {
    pub definition: FormulaDefinition,
    pub status: FormulaStatus,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub enum FormulaStatus {
    Ready { output_type: ValueType },
    NotReady,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct FormulaEngineChangeResult {
    pub affected_formulas: Vec<PropertyId>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
pub enum Value {
    Number(f64),
    String(String),
    Boolean(bool),
    Date(#[serde(deserialize_with = "deserialize_i64_bigint")] i64),
    List(Vec<Option<Value>>),
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields)]
pub struct ColumnData<T> {
    pub values: Vec<T>,
    pub validity: Vec<bool>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
pub enum Column {
    Number(ColumnData<f64>),
    String(ColumnData<String>),
    Boolean(ColumnData<bool>),
    Date(#[serde(deserialize_with = "deserialize_date_column")] ColumnData<i64>),
    List(ColumnData<Vec<Option<Value>>>),
    Union(ColumnData<Value>),
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
pub enum ColumnKind {
    Number,
    String,
    Boolean,
    Date,
    List,
    Union,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields)]
pub struct RuntimeContext {
    #[serde(deserialize_with = "deserialize_i64_bigint")]
    pub now: i64,
    pub time_zone: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields)]
pub struct EvaluateInput {
    pub row_ids: Vec<RowId>,
    #[serde(deserialize_with = "deserialize_columns")]
    #[ts(type = "Map<PropertyId, Column>")]
    pub columns: HashMap<PropertyId, Column>,
    pub runtime: RuntimeContext,
    pub formula_ids: Vec<PropertyId>,
}
#[derive(Debug, Clone, PartialEq, Serialize, TS)]
pub struct EvaluateResult {
    #[ts(
        type = "Map<PropertyId, { Ok: FormulaOutput } | { Err: FormulaEvaluationError }>"
    )]
    pub formulas: HashMap<PropertyId, Result<FormulaOutput, FormulaEvaluationError>>,
}
#[derive(Debug, Clone, PartialEq, Serialize, TS)]
pub struct FormulaOutput {
    pub output_type: ValueType,
    pub column: Column,
    pub errors: Vec<RowError>,
}
#[derive(Debug, Clone, PartialEq, Serialize, TS)]
pub struct RowError {
    pub row_index: u32,
    pub origin_formula_id: PropertyId,
    pub error: RuntimeError,
}
#[derive(Debug, Clone, PartialEq, Serialize, TS)]
pub enum RuntimeError {
    InvalidValueType { expected: ValueType, actual: ValueType },
    InvalidValue { actual: Value, constraint: String },
    InvalidRegex { pattern: String, detail: String },
    InvalidDateText { text: String },
    DateOutOfRange,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub enum FormulaEvaluationError {
    NotReady,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub enum FormulaEngineInitError {
    EmptyId,
    DuplicateId(PropertyId),
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub enum EngineChangeError {
    EmptyId,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub enum CreateDraftError {
    EmptyId,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub enum EvaluateInputError {
    InvalidNow { now: i64 },
    InvalidTimeZone { time_zone: String },
    EmptyRowId { row_index: u32 },
    DuplicateRowId { id: RowId },
    EmptyFormulaIds,
    InvalidFormulaId { id: PropertyId },
    DuplicateFormulaId { id: PropertyId },
    MissingInputs { ids: Vec<PropertyId> },
    UnexpectedInputs { ids: Vec<PropertyId> },
    InvalidColumnType { id: PropertyId, expected: ColumnKind, actual: ColumnKind },
    InvalidColumnLength {
        id: PropertyId,
        expected: u32,
        values_len: u32,
        validity_len: u32,
    },
    InvalidValueType {
        id: PropertyId,
        row_index: u32,
        element_path: Vec<u32>,
        expected: ValueType,
        actual: ValueType,
    },
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields)]
pub struct CompletionConfig {
    pub preferred_limit: u32,
}
#[derive(Serialize, TS)]
pub struct FormulaDraftState {
    pub version: DraftVersion,
    pub definition: FormulaDefinition,
    pub output_type: ValueType,
    pub diagnostics: Vec<ExpressionDiagnostic>,
    pub tokens: Vec<Token>,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct ExpressionDiagnostic {
    pub id: DiagnosticId,
    pub span: Span,
    pub message: String,
}
#[derive(Serialize, TS)]
pub struct CompletionResult {
    pub items: Vec<CompletionItem>,
    pub replace: Span,
    pub preferred_indices: Vec<u32>,
}
#[derive(Serialize, TS)]
pub struct SignatureHelp {
    pub signatures: Vec<SignatureItem>,
    pub active_signature: u32,
    pub active_parameter: u32,
}
#[derive(Serialize, TS)]
pub struct CursorHelp {
    pub base_version: DraftVersion,
    pub completion: CompletionResult,
    pub signature_help: Option<SignatureHelp>,
}
#[derive(Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields)]
pub struct FormulaEdit {
    #[serde(deserialize_with = "deserialize_u64_bigint")]
    pub base_version: DraftVersion,
    pub edits: Vec<TextEdit>,
}
#[derive(Serialize, Deserialize, TS)]
pub enum ExpressionUpdate {
    Replace(String),
    Edits { edit: FormulaEdit, cursor: TextOffset },
}
#[derive(Serialize, TS)]
pub struct QuickFix {
    pub title: String,
    pub edit: FormulaEdit,
}
#[derive(Serialize, TS)]
pub struct UpdateExpressionResult {
    pub state: FormulaDraftState,
    pub cursor: TextOffset,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, TS)]
pub enum UpdateExpressionError {
    VersionMismatch,
    InvalidCursor,
    InvalidEditRange,
    OverlappingEdits,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct InvalidDtoPayload {
    pub operation: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct DraftClosedPayload {
    pub handle: u32,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct ActiveDraftsPayload {
    pub count: u32,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct EngineInitPayload {
    pub error: FormulaEngineInitError,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct EngineChangePayload {
    pub error: EngineChangeError,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct CreateDraftPayload {
    pub error: CreateDraftError,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct EvaluateInputPayload {
    pub error: EvaluateInputError,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct UpdateExpressionPayload {
    pub error: UpdateExpressionError,
}
/// Controlled WASM failures are cloned across the Worker boundary as plain data.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(tag = "code", rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FormulaClientErrorData {
    InvalidDto { message: String, payload: InvalidDtoPayload },
    EngineClosed { message: String, payload: () },
    DraftClosed { message: String, payload: DraftClosedPayload },
    ActiveDrafts { message: String, payload: ActiveDraftsPayload },
    EngineInit { message: String, payload: EngineInitPayload },
    EngineChange { message: String, payload: EngineChangePayload },
    CreateDraft { message: String, payload: CreateDraftPayload },
    EvaluateInput { message: String, payload: EvaluateInputPayload },
    UpdateExpression { message: String, payload: UpdateExpressionPayload },
    FormatError { message: String, payload: () },
    SerializeError { message: String, payload: () },
    /// Emitted by the JS host when the Worker crashes or its transport fails.
    WorkerFailure { message: String, payload: () },
    /// Emitted by the JS host for a malformed Worker response.
    InvalidResponse { message: String, payload: () },
    /// Emitted by the JS host for an invalid RPC request.
    InvalidRequest { message: String, payload: () },
    /// Emitted by the JS host when creating the Worker or loading WASM fails.
    InitializationError { message: String, payload: () },
}
