// Generated by md-first. DO NOT EDIT.
// Source: md-first/docs/specs/README.md

use std::path::{Path, PathBuf};
use crate::{Error, Preprocessor};
#[derive(Default)]
pub struct Dispatcher {
    inner: DispatcherInner,
}
impl Dispatcher {
    /// Create an empty Preprocessor registry.
    pub fn new() -> Self {
        Self::new_impl()
    }
    /// Each out uses the Preprocessor with the longest matching suffix.
    /// - error: the suffix is empty or already registered.
    pub fn register(
        &mut self,
        suffix: impl Into<String>,
        preprocessor: impl Preprocessor + 'static,
    ) -> Result<(), Error> {
        Self::register_impl(self, suffix, preprocessor)
    }
    /// Read the configuration, generate and overwrite each out, and create parent directories as needed.
    /// Return project-relative output paths sorted by path.
    /// Each file begins with a DO NOT EDIT notice and source Markdown paths, deduplicated in input order.
    /// - error: configuration, read, lexing, or preprocessing failure; no matching Preprocessor for an out.
    ///   These errors leave all outputs untouched; I/O errors during writes do not guarantee rollback.
    pub fn generate(
        &self,
        project_root: impl AsRef<Path>,
    ) -> Result<Vec<PathBuf>, Error> {
        Self::generate_impl(self, project_root)
    }
    /// Regenerate in memory and compare file contents without writing any files.
    /// - error: generation fails, or an output file is missing or differs.
    pub fn check(&self, project_root: impl AsRef<Path>) -> Result<(), Error> {
        Self::check_impl(self, project_root)
    }
}
