// Generated by md-first. DO NOT EDIT.
// Source: md-first/docs/specs/README.zh-CN.md

use std::path::{Path, PathBuf};
use crate::{Error, Preprocessor};
#[derive(Default)]
pub struct Dispatcher {
    inner: DispatcherInner,
}
impl Dispatcher {
    /// 创建空的 Preprocessor 注册表。
    pub fn new() -> Self {
        Self::new_impl()
    }
    /// 每个 out 选择匹配后缀最长的 Preprocessor。
    /// - error: 后缀为空或已注册。
    pub fn register(
        &mut self,
        suffix: impl Into<String>,
        preprocessor: impl Preprocessor + 'static,
    ) -> Result<(), Error> {
        Self::register_impl(self, suffix, preprocessor)
    }
    /// 读取配置，生成并覆盖各 out；自动创建父目录，返回按路径排序的项目相对输出路径。
    /// 文件顶部包含 DO NOT EDIT 提示及来源 Markdown 路径，来源按输入顺序去重。
    /// - error: 配置、读取、分词或预处理失败；out 没有匹配的 Preprocessor。
    ///   这些错误发生时不写入任何输出；写入阶段的 I/O 错误不保证整体回滚。
    pub fn generate(
        &self,
        project_root: impl AsRef<Path>,
    ) -> Result<Vec<PathBuf>, Error> {
        Self::generate_impl(self, project_root)
    }
    /// 在内存中重新生成并比较文件内容，全程不写入。
    /// - error: 生成失败，或输出文件缺失、内容不同。
    pub fn check(&self, project_root: impl AsRef<Path>) -> Result<(), Error> {
        Self::check_impl(self, project_root)
    }
}
