use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use proc_macro2::TokenStream;
use syn::visit::{self, Visit};

use crate::{BlockSource, Error};

pub(crate) fn render(tokens: TokenStream, sources: &[BlockSource]) -> String {
    let mut result = String::from("// Generated by md-first. DO NOT EDIT.\n");
    let mut seen = BTreeSet::new();
    for source in sources {
        if seen.insert(&source.document) {
            let path = source
                .document
                .to_string_lossy()
                .replace('\\', "/")
                .replace(['\n', '\r'], " ");
            result.push_str(&format!("// Source: {path}\n"));
        }
    }
    result.push('\n');
    // Formatting is optional: a processor may return a Rust-like DSL, or syntax
    // that syn preserves verbatim. Neither is a dispatcher grammar restriction.
    if let Ok(file) = syn::parse2::<syn::File>(tokens.clone()) {
        let mut verbatim = Verbatim(false);
        verbatim.visit_file(&file);
        if !verbatim.0 {
            result.push_str(&prettyplease::unparse(&file));
            return result;
        }
    }
    result.push_str(&tokens.to_string());
    result.push('\n');
    result
}

pub(crate) fn write(root: &Path, files: &BTreeMap<PathBuf, String>) -> Result<(), Error> {
    for path in files.keys() {
        validate_destination(root, path)?;
    }
    for (relative, contents) in files {
        let path = root.join(relative);
        let directory = path.parent().expect("project-relative output has a parent");
        fs::create_dir_all(directory).map_err(|error| Error::io(directory, error))?;
        if fs::read(&path).ok().as_deref() != Some(contents.as_bytes()) {
            fs::write(&path, contents).map_err(|error| Error::io(&path, error))?;
        }
    }
    Ok(())
}

pub(crate) fn check(root: &Path, files: &BTreeMap<PathBuf, String>) -> Result<(), Error> {
    let mut errors = Vec::new();
    for (relative, expected) in files {
        validate_destination(root, relative)?;
        let path = root.join(relative);
        match fs::read(&path) {
            Ok(actual) if actual == expected.as_bytes() => {}
            Ok(_) => errors.push(format!("{}: generated output is stale", relative.display())),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                errors.push(format!(
                    "{}: generated output is missing",
                    relative.display()
                ));
            }
            Err(error) => errors.push(format!("{}: {error}", relative.display())),
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(Error(errors))
    }
}

fn validate_destination(root: &Path, relative: &Path) -> Result<(), Error> {
    let mut path = root.join(relative);
    loop {
        match fs::canonicalize(&path) {
            Ok(canonical) if canonical.starts_with(root) => return Ok(()),
            Ok(_) => {
                return Err(Error::new(format!(
                    "{}: output escapes project root through a symlink",
                    relative.display()
                )));
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                // A dangling symlink exists even though canonicalize cannot
                // resolve it. Do not fall back to its parent and then follow it.
                if fs::symlink_metadata(&path).is_ok_and(|metadata| metadata.is_symlink())
                    || !path.pop()
                {
                    return Err(Error::io(&path, error));
                }
            }
            Err(error) => return Err(Error::io(&path, error)),
        }
    }
}

struct Verbatim(bool);

macro_rules! visit_verbatim {
    ($($method:ident: $ty:ident),* $(,)?) => { $(
        fn $method(&mut self, item: &'ast syn::$ty) {
            if matches!(item, syn::$ty::Verbatim(_)) { self.0 = true; }
            else { visit::$method(self, item); }
        }
    )* };
}

impl<'ast> Visit<'ast> for Verbatim {
    visit_verbatim!(visit_item: Item, visit_impl_item: ImplItem, visit_trait_item: TraitItem,
        visit_foreign_item: ForeignItem, visit_expr: Expr, visit_pat: Pat, visit_type: Type);
}
