// Generated by md-first. DO NOT EDIT.
// Source: md-first/docs/specs/README.md

use std::path::PathBuf;
use proc_macro2::{Span, TokenStream};
/// # Examples
///
/// ```
/// use md_first_core::{Context, Dispatcher, Preprocessor};
/// use proc_macro2::TokenStream;
///
/// // 1. Define how blocks with the same out are combined
/// struct Merge;
/// impl Preprocessor for Merge {
///     fn preprocess(&self, blocks: Vec<TokenStream>, _context: &Context) -> TokenStream {
///         blocks.into_iter().collect()
///     }
/// }
///
/// // 2. Register the preprocessor for an output suffix
/// let mut dispatcher = Dispatcher::new();
/// dispatcher.register(".rs", Merge)?;
/// # Ok::<(), md_first_core::Error>(())
/// ```
pub trait Preprocessor {
    /// Receive all blocks for one out in a single call, sorted by project-relative document path,
    /// then by their order within each document.
    /// Each block is tokenized independently; delimiters must balance, but complete Rust items are not required.
    /// The Preprocessor decides how to parse and combine blocks and whether declarations across documents are valid.
    /// The returned TokenStream is serialized and written to out.
    fn preprocess(&self, blocks: Vec<TokenStream>, context: &Context) -> TokenStream;
}
pub struct Context {
    /// Absolute path.
    pub project_root: PathBuf,
    /// Relative to project_root.
    pub out: PathBuf,
    /// `sources[i]` corresponds to `blocks[i]`.
    pub sources: Vec<BlockSource>,
    inner: ContextInner,
}
impl Context {
    /// Use a span from `blocks[block_index]` to report an error at the original Markdown location.
    /// This generation fails without writing any outputs.
    pub fn error(&self, block_index: usize, span: Span, message: impl Into<String>) {
        Self::error_impl(self, block_index, span, message)
    }
}
#[derive(Clone, Debug)]
pub struct BlockSource {
    /// Relative to project_root.
    pub document: PathBuf,
    /// First line of code in the original Markdown, 1-based; use Context::error for precise diagnostics.
    pub start_line: usize,
}
