// Generated by md-first. DO NOT EDIT.
// Source: md-first/docs/specs/README.zh-CN.md

use std::path::PathBuf;
use proc_macro2::{Span, TokenStream};
/// # Examples
///
/// ```
/// use md_first_core::{Context, Dispatcher, Preprocessor};
/// use proc_macro2::TokenStream;
///
/// // 1. Define how blocks with the same out are combined
/// struct Merge;
/// impl Preprocessor for Merge {
///     fn preprocess(&self, blocks: Vec<TokenStream>, _context: &Context) -> TokenStream {
///         blocks.into_iter().collect()
///     }
/// }
///
/// // 2. Register the preprocessor for an output suffix
/// let mut dispatcher = Dispatcher::new();
/// dispatcher.register(".rs", Merge)?;
/// # Ok::<(), md_first_core::Error>(())
/// ```
pub trait Preprocessor {
    /// 同一 out 的 blocks 一次传入；跨文档按项目相对路径排序，文档内按出现顺序排列。
    /// 每个 block 独立分词，分隔符必须配对，无需包含完整 Rust item。
    /// 解析、合并及跨文档声明是否合法，由 Preprocessor 决定；返回值序列化后写入 out。
    fn preprocess(&self, blocks: Vec<TokenStream>, context: &Context) -> TokenStream;
}
pub struct Context {
    /// 绝对路径。
    pub project_root: PathBuf,
    /// 相对 project_root。
    pub out: PathBuf,
    /// `sources[i]` 对应 `blocks[i]`。
    pub sources: Vec<BlockSource>,
    inner: ContextInner,
}
impl Context {
    /// span 来自 `blocks[block_index]`；错误定位到原始 Markdown，本轮生成失败且不写入输出。
    pub fn error(&self, block_index: usize, span: Span, message: impl Into<String>) {
        Self::error_impl(self, block_index, span, message)
    }
}
#[derive(Clone, Debug)]
pub struct BlockSource {
    /// 相对 project_root。
    pub document: PathBuf,
    /// 代码内容在原始 Markdown 中的起始行，1-based；精确诊断使用 Context::error。
    pub start_line: usize,
}
