use std::fmt::Write;

#[cfg(test)]
use std::collections::HashSet;

use builtin_fn::{BuiltinCategory, FunctionSig, ParamRef, ParamSig, Ty};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Mode {
    Value,
    Controlled,
}

pub fn generate_contract(categories: &[BuiltinCategory]) -> String {
    let functions = categories
        .iter()
        .flat_map(|category| category.entries.iter())
        .filter_map(|entry| entry.implementation.as_ref())
        .collect::<Vec<_>>();

    generate_contract_for_functions(&functions)
}

/// Generate a bounded fixture from the real catalog without copying declarations.
#[cfg(test)]
pub fn generate_contract_for_names(
    categories: &[BuiltinCategory],
    names: &[&str],
) -> Result<String, String> {
    let mut requested = HashSet::with_capacity(names.len());
    for name in names {
        if !requested.insert(*name) {
            return Err(format!("duplicate generated-contract selection `{name}`"));
        }
    }

    let mut functions = Vec::with_capacity(names.len());
    for category in categories {
        for entry in &category.entries {
            if !requested.contains(entry.name.as_str()) {
                continue;
            }
            let Some(signature) = entry.implementation.as_ref() else {
                return Err(format!(
                    "unsupported builtin `{}` has no evaluator contract",
                    entry.name
                ));
            };
            functions.push(signature);
        }
    }
    for name in names {
        if !functions.iter().any(|signature| signature.name == *name) {
            return Err(format!("unknown builtin `{name}`"));
        }
    }

    Ok(generate_contract_for_functions(&functions))
}

fn generate_contract_for_functions(functions: &[&FunctionSig]) -> String {
    let mut out = String::new();
    writeln!(out, "// @generated by evaluator/build.rs; do not edit.\n").unwrap();
    emit_key(&mut out, functions);
    emit_common_metadata(&mut out, functions);
    for signature in functions {
        emit_function_contract(&mut out, signature);
    }
    emit_dispatch(&mut out, functions, Mode::Value);
    emit_dispatch(&mut out, functions, Mode::Controlled);
    out
}

fn emit_key(out: &mut String, functions: &[&FunctionSig]) {
    writeln!(
        out,
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]\npub(crate) enum BuiltinKey {{"
    )
    .unwrap();
    for signature in functions {
        writeln!(out, "    {},", rust_type_name(&signature.name)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    writeln!(out, "impl BuiltinKey {{").unwrap();
    writeln!(out, "    #[allow(dead_code)]").unwrap();
    writeln!(out, "    pub(crate) const ALL: &'static [Self] = &[").unwrap();
    for signature in functions {
        writeln!(out, "        Self::{},", rust_type_name(&signature.name)).unwrap();
    }
    writeln!(out, "    ];").unwrap();
    writeln!(
        out,
        "    pub(crate) fn from_name(name: &str) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(out, "        match name {{").unwrap();
    for signature in functions {
        writeln!(
            out,
            "            {:?} => ::core::option::Option::Some(Self::{}),",
            signature.name,
            rust_type_name(&signature.name)
        )
        .unwrap();
    }
    writeln!(out, "            _ => ::core::option::Option::None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    pub(crate) const fn name(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for signature in functions {
        writeln!(
            out,
            "            Self::{} => {:?},",
            rust_type_name(&signature.name),
            signature.name
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
}

fn emit_common_metadata(out: &mut String, functions: &[&FunctionSig]) {
    writeln!(
        out,
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub(crate) enum BuiltinEvaluationMode {{ Value, Controlled }}\n"
    )
    .unwrap();
    writeln!(out, "impl BuiltinKey {{").unwrap();
    writeln!(
        out,
        "    pub(crate) const fn evaluation_mode(self) -> BuiltinEvaluationMode {{"
    )
    .unwrap();
    writeln!(out, "        match self {{").unwrap();
    for signature in functions {
        let mode = match mode(signature) {
            Mode::Value => "Value",
            Mode::Controlled => "Controlled",
        };
        writeln!(
            out,
            "            Self::{} => BuiltinEvaluationMode::{mode},",
            rust_type_name(&signature.name)
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    pub(crate) const fn return_abi(self) -> AbiKind {{"
    )
    .unwrap();
    writeln!(out, "        match self {{").unwrap();
    for signature in functions {
        writeln!(
            out,
            "            Self::{} => AbiKind::{},",
            rust_type_name(&signature.name),
            abi_name(&signature.ret)
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();

    writeln!(
        out,
        "pub(crate) trait BuiltinContract {{\n    const KEY: BuiltinKey;\n    fn signature() -> &'static FunctionSig {{ signature_for_key(Self::KEY) }}\n}}\n"
    )
    .unwrap();
}

fn emit_function_contract(out: &mut String, signature: &FunctionSig) {
    let base = rust_type_name(&signature.name);
    let mode = mode(signature);
    let args_name = match mode {
        Mode::Value => format!("{base}Args"),
        Mode::Controlled => format!("{base}Plans"),
    };
    let repeat_name = format!("{base}RepeatGroup");
    let trait_name = format!("{base}Kernel");
    let return_kind = kind_name(&signature.ret);

    writeln!(out, "pub(crate) struct {base};").unwrap();
    writeln!(out, "impl BuiltinContract for {base} {{").unwrap();
    writeln!(out, "    const KEY: BuiltinKey = BuiltinKey::{base};\n}}").unwrap();

    if !signature.params.repeat.is_empty() {
        writeln!(out, "pub(crate) struct {repeat_name} {{").unwrap();
        for param in &signature.params.repeat {
            writeln!(
                out,
                "    pub(crate) {}: {},",
                rust_field_name(&param.name),
                field_type(param, mode)
            )
            .unwrap();
        }
        writeln!(out, "}}").unwrap();
    }

    writeln!(out, "pub(crate) struct {args_name} {{").unwrap();
    for param in &signature.params.head {
        writeln!(
            out,
            "    pub(crate) {}: {},",
            rust_field_name(&param.name),
            field_type(param, mode)
        )
        .unwrap();
    }
    if !signature.params.repeat.is_empty() {
        writeln!(
            out,
            "    pub(crate) repeat_groups: RepeatGroups<{repeat_name}>,"
        )
        .unwrap();
    }
    for param in &signature.params.tail {
        writeln!(
            out,
            "    pub(crate) {}: {},",
            rust_field_name(&param.name),
            field_type(param, mode)
        )
        .unwrap();
    }
    writeln!(out, "}}").unwrap();

    if mode == Mode::Value {
        emit_into_dynamic(out, signature, mode, &args_name);
    }

    match mode {
        Mode::Value => {
            writeln!(out, "pub(crate) trait {trait_name} {{").unwrap();
            writeln!(
                out,
                "    fn eval<C: BuiltinValueContext>(args: {args_name}, context: &C, mask: &Mask) -> KernelResult<{return_kind}>;"
            )
            .unwrap();
            writeln!(out, "}}\n").unwrap();
        }
        Mode::Controlled => {
            writeln!(out, "pub(crate) trait {trait_name} {{").unwrap();
            writeln!(
                out,
                "    fn eval<C: BuiltinEvalContext>(context: &mut C, args: {args_name}, mask: &Mask) -> KernelResult<{return_kind}>;"
            )
            .unwrap();
            writeln!(out, "}}\n").unwrap();
        }
    }
}

fn emit_into_dynamic(out: &mut String, signature: &FunctionSig, mode: Mode, args_name: &str) {
    let dynamic = match mode {
        Mode::Value => "DynamicValueArgs",
        Mode::Controlled => "DynamicControlledArgs",
    };
    writeln!(out, "impl {args_name} {{").unwrap();
    writeln!(out, "    #[allow(dead_code)]").unwrap();
    writeln!(out, "    pub(crate) fn into_dynamic(self) -> {dynamic} {{").unwrap();
    writeln!(out, "        {dynamic}::new(").unwrap();
    writeln!(out, "            vec![").unwrap();
    for param in &signature.params.head {
        writeln!(
            out,
            "                {},",
            erase_field_expr(
                param,
                &format!("self.{}", rust_field_name(&param.name)),
                mode
            )
        )
        .unwrap();
    }
    writeln!(out, "            ],").unwrap();
    if signature.params.repeat.is_empty() {
        writeln!(out, "            Vec::new(),").unwrap();
    } else {
        writeln!(
            out,
            "            self.repeat_groups.into_vec().into_iter().map(|group| vec!["
        )
        .unwrap();
        for param in &signature.params.repeat {
            writeln!(
                out,
                "                {},",
                erase_field_expr(
                    param,
                    &format!("group.{}", rust_field_name(&param.name)),
                    mode
                )
            )
            .unwrap();
        }
        writeln!(out, "            ]).collect(),").unwrap();
    }
    writeln!(out, "            vec![").unwrap();
    for param in &signature.params.tail {
        writeln!(
            out,
            "                {},",
            erase_field_expr(
                param,
                &format!("self.{}", rust_field_name(&param.name)),
                mode
            )
        )
        .unwrap();
    }
    writeln!(out, "            ],").unwrap();
    writeln!(out, "        )").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
}

fn emit_dispatch(out: &mut String, functions: &[&FunctionSig], selected_mode: Mode) {
    match selected_mode {
        Mode::Value => {
            writeln!(
                out,
                "pub(crate) fn dispatch_value<C: BuiltinValueContext>(\n    key: BuiltinKey,\n    mut prepared: PreparedValueArguments,\n    context: &C,\n    debug_contract: Option<&DebugCallContract>,\n) -> EvalBlock {{\n    match key {{"
            )
            .unwrap();
        }
        Mode::Controlled => {
            writeln!(
                out,
                "pub(crate) fn dispatch_controlled<C: BuiltinEvalContext>(\n    key: BuiltinKey,\n    context: &mut C,\n    mut prepared: PreparedControlledArguments,\n    mask: &Mask,\n    debug_contract: Option<&DebugCallContract>,\n) -> EvalBlock {{\n    match key {{"
            )
            .unwrap();
        }
    }

    for signature in functions
        .iter()
        .copied()
        .filter(|sig| mode(sig) == selected_mode)
    {
        emit_dispatch_arm(out, signature, selected_mode);
    }
    let other_mode = match selected_mode {
        Mode::Value => Mode::Controlled,
        Mode::Controlled => Mode::Value,
    };
    let other_variants = functions
        .iter()
        .copied()
        .filter(|sig| mode(sig) == other_mode)
        .map(|sig| format!("BuiltinKey::{}", rust_type_name(&sig.name)))
        .collect::<Vec<_>>();
    if !other_variants.is_empty() {
        writeln!(out, "        {} => {{", other_variants.join(" | ")).unwrap();
        match selected_mode {
            Mode::Value => writeln!(out, "            prepared.invalid_mode(key)").unwrap(),
            Mode::Controlled => {
                writeln!(out, "            prepared.invalid_mode(key, mask)").unwrap()
            }
        }
        writeln!(out, "        }}").unwrap();
    }
    writeln!(out, "    }}\n}}\n").unwrap();
}

fn emit_dispatch_arm(out: &mut String, signature: &FunctionSig, mode: Mode) {
    let base = rust_type_name(&signature.name);
    let args_name = match mode {
        Mode::Value => format!("{base}Args"),
        Mode::Controlled => format!("{base}Plans"),
    };
    let trait_name = format!("{base}Kernel");
    let return_kind = kind_name(&signature.ret);
    writeln!(out, "        BuiltinKey::{base} => {{").unwrap();
    writeln!(
        out,
        "            debug_assert_eq!(<{base} as BuiltinContract>::signature().name, key.name());"
    )
    .unwrap();
    writeln!(out, "            #[allow(clippy::redundant_closure_call)]").unwrap();
    writeln!(
        out,
        "            let args = (|| -> Result<{args_name}, PreparedArgumentError> {{"
    )
    .unwrap();
    writeln!(out, "                Ok({args_name} {{").unwrap();
    for (index, param) in signature.params.head.iter().enumerate() {
        writeln!(
            out,
            "                    {}: {},",
            rust_field_name(&param.name),
            take_expr(
                param,
                ParamRef::Head(index),
                mode,
                "::core::option::Option::None"
            )
        )
        .unwrap();
    }
    if !signature.params.repeat.is_empty() {
        let repeat_name = format!("{base}RepeatGroup");
        writeln!(out, "                    repeat_groups: RepeatGroups::new((1..=prepared.repeat_group_count()).map(|group| -> Result<{repeat_name}, PreparedArgumentError> {{").unwrap();
        writeln!(out, "                        Ok({repeat_name} {{").unwrap();
        for (index, param) in signature.params.repeat.iter().enumerate() {
            writeln!(
                out,
                "                            {}: {},",
                rust_field_name(&param.name),
                take_expr(
                    param,
                    ParamRef::Repeat(index),
                    mode,
                    "::core::option::Option::Some(group)"
                )
            )
            .unwrap();
        }
        writeln!(out, "                        }})").unwrap();
        writeln!(
            out,
            "                    }}).collect::<Result<Vec<_>, _>>()?),"
        )
        .unwrap();
    }
    for (index, param) in signature.params.tail.iter().enumerate() {
        writeln!(
            out,
            "                    {}: {},",
            rust_field_name(&param.name),
            take_expr(
                param,
                ParamRef::Tail(index),
                mode,
                "::core::option::Option::None"
            )
        )
        .unwrap();
    }
    writeln!(out, "                }})").unwrap();
    writeln!(out, "            }})();").unwrap();
    match mode {
        Mode::Value => {
            writeln!(out, "            let args = match args {{ Ok(args) => args, Err(error) => return prepared.contract_failure(error), }};").unwrap();
            writeln!(
                out,
                "            let kernel_mask = prepared.eligible().clone();"
            )
            .unwrap();
            writeln!(
                out,
                "            let result = <{base} as {trait_name}>::eval(args, context, &kernel_mask);"
            )
            .unwrap();
            writeln!(
                out,
                "            prepared.finish::<{return_kind}>(result, key, debug_contract)"
            )
            .unwrap();
        }
        Mode::Controlled => {
            writeln!(out, "            let args = match args {{ Ok(args) => args, Err(error) => return prepared.contract_failure(error, mask), }};").unwrap();
            writeln!(
                out,
                "            let result = <{base} as {trait_name}>::eval(context, args, mask);"
            )
            .unwrap();
            writeln!(
                out,
                "            finish_controlled_result::<{return_kind}>(result, key, mask, debug_contract)"
            )
            .unwrap();
        }
    }
    writeln!(out, "        }}").unwrap();
}

fn take_expr(param: &ParamSig, reference: ParamRef, mode: Mode, group: &str) -> String {
    let reference = match reference {
        ParamRef::Head(index) => format!("ParamRef::Head({index})"),
        ParamRef::Repeat(index) => format!("ParamRef::Repeat({index})"),
        ParamRef::Tail(index) => format!("ParamRef::Tail({index})"),
    };
    let kind = kind_name(match &param.ty {
        Ty::Fn { ret, .. } => ret,
        Ty::Ident(inner) => inner,
        ty => ty,
    });
    let method = match (&param.ty, mode) {
        (_, Mode::Value) => "take_value",
        (Ty::Fn { params, .. }, Mode::Controlled) if params.is_empty() => "take_thunk",
        (Ty::Fn { .. }, Mode::Controlled) => "take_lambda",
        (Ty::Ident(_), Mode::Controlled) => "take_binder",
        (_, Mode::Controlled) => "take_value",
    };
    let call = format!("prepared.{method}::<{kind}>({reference}, {group})?");
    if param.optional {
        format!(
            "prepared.take_optional_{method_suffix}::<{kind}>({reference}, {group})?",
            method_suffix = method.strip_prefix("take_").unwrap_or(method)
        )
    } else {
        call
    }
}

fn field_type(param: &ParamSig, mode: Mode) -> String {
    let base = match mode {
        Mode::Value => format!("KernelColumn<{}>", kind_name(&param.ty)),
        Mode::Controlled => match &param.ty {
            Ty::Fn { params, ret } if params.is_empty() => {
                format!("ThunkPlan<{}>", kind_name(ret))
            }
            Ty::Fn { ret, .. } => format!("LambdaPlan<{}>", kind_name(ret)),
            Ty::Ident(inner) => format!("BinderHandle<{}>", kind_name(inner)),
            ty => format!("ValuePlan<{}>", kind_name(ty)),
        },
    };
    if param.optional {
        format!("Option<{base}>")
    } else {
        base
    }
}

fn erase_field_expr(param: &ParamSig, expression: &str, mode: Mode) -> String {
    let erased = match mode {
        Mode::Value => format!("{expression}.into_column()"),
        Mode::Controlled => format!("{expression}.into_dynamic()"),
    };
    if param.optional {
        let inner = match mode {
            Mode::Value => "value.into_column()",
            Mode::Controlled => "value.into_dynamic()",
        };
        format!("{expression}.map(|value| {inner})")
    } else {
        format!("::core::option::Option::Some({erased})")
    }
}

fn mode(signature: &FunctionSig) -> Mode {
    if signature
        .display_params()
        .iter()
        .any(|param| matches!(param.ty, Ty::Fn { .. } | Ty::Ident(_)))
    {
        Mode::Controlled
    } else {
        Mode::Value
    }
}

fn abi_name(ty: &Ty) -> &'static str {
    match ty {
        Ty::Number => "Number",
        Ty::Boolean => "Boolean",
        Ty::String => "Text",
        Ty::Date => "Date",
        Ty::List(_) => "List",
        Ty::Union(members) => {
            let mut kinds = members
                .iter()
                .filter(|member| !matches!(member, Ty::Null))
                .map(abi_name);
            let Some(first) = kinds.next() else {
                return "Any";
            };
            if kinds.all(|kind| kind == first) {
                first
            } else {
                "Any"
            }
        }
        Ty::Null | Ty::Unknown | Ty::Generic(_) | Ty::Fn { .. } | Ty::Ident(_) => "Any",
    }
}

fn kind_name(ty: &Ty) -> &'static str {
    match abi_name(ty) {
        "Number" => "NumberKind",
        "Boolean" => "BooleanKind",
        "Text" => "TextKind",
        "Date" => "DateKind",
        "List" => "ListKind",
        _ => "AnyKind",
    }
}

fn rust_type_name(name: &str) -> String {
    let mut out = String::new();
    let mut uppercase_next = true;
    for ch in name.chars() {
        if ch == '_' || ch == '-' {
            uppercase_next = true;
        } else if uppercase_next {
            out.extend(ch.to_uppercase());
            uppercase_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn rust_field_name(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    if matches!(
        out.as_str(),
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    ) {
        out.push('_');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{rust_field_name, rust_type_name};

    #[test]
    fn rust_names_are_stable() {
        assert_eq!(rust_type_name("dateAdd"), "DateAdd");
        assert_eq!(rust_field_name("startIndex"), "start_index");
        assert_eq!(rust_field_name("else"), "else_");
    }
}
