// Generated by md-first. DO NOT EDIT.
// Source: docs/specs/formula-engine.zh-CN.md

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaSchema {
    pub properties: Vec<PropertyDefinition>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PropertyDefinition {
    Input { id: PropertyId, ty: ValueType },
    Formula(FormulaDefinition),
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaDefinition {
    pub id: PropertyId,
    /// 公式定义，可通过 prop("id") 按 ID 引用同一 FormulaSchema 中其它 Property。
    pub expression: String,
}
/// 由调用方指定的稳定 ID。
///
/// - Input 与 Formula 共用同一命名空间；Engine 校验 ID 非空及 FormulaSchema 内唯一。
/// - 不限制字符串格式；区分大小写，不做 Unicode 归一化。
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, derive_more::From)]
#[from(String, &str)]
pub struct PropertyId(pub String);
/// Input 的声明类型与 Formula 的推断类型。
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ValueType {
    /// 数值规则见 [Planned Number](formula-language.zh-CN.md#planned-number)。
    Number,
    String,
    Boolean,
    Date,
    /// 静态类型未确定；可用于 Input 声明和推断结果，包括嵌套类型。
    /// 未知部分允许所有 Value 类型，具体操作在运行时校验实际类型。
    Unknown,
    List(Box<ValueType>),
    Union(Vec<ValueType>),
}
#[derive(Debug, PartialEq, Eq)]
pub enum FormulaEngineState<'a> {
    /// 无环且所有公式均为 Ready。
    AllReady,
    /// 即使有公式尚未就绪，其他公式仍可保持 Ready。
    NotAllReady {
        /// 有环时返回一条路径；前一个 ID 直接依赖后一个 ID，首尾 ID 相同。
        /// - empty: 无环路，仍有未 Ready 的公式。
        /// - [A, A]: 自引用 A -> A
        /// - [A, B, C, A]: 环路 A -> B -> C -> A
        cycle_path: &'a [PropertyId],
    },
}
/// 字段定义与状态的独立快照，不随 Engine 后续更新而变化。
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PropertyState {
    Input { id: PropertyId, ty: ValueType },
    Formula(FormulaState),
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaState {
    pub definition: FormulaDefinition,
    pub status: FormulaStatus,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FormulaStatus {
    /// 公式自身及其依赖都可以执行。
    /// output_type 可包含 Unknown；例如 [] 为 Ready，类型为 List(Unknown)。
    Ready { output_type: ValueType },
    NotReady,
}
/// FormulaEngine::upsert / remove 的变更结果。
#[derive(Debug, PartialEq, Eq)]
pub struct FormulaEngineChangeResult {
    /// 受本次变更影响的 Formula ID，包括直接、间接依赖者。
    /// - 仅包含变更后仍存在的 Formula。
    /// - upsert 新增或修改 Formula 时，也包含它自身。
    /// - 定义内容没有发生变化时为空。
    pub affected_formulas: Vec<PropertyId>,
}
/// FormulaEngine::new 接收的定义不合法。
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FormulaEngineInitError {
    EmptyId,
    DuplicateId(PropertyId),
}
/// FormulaEngine::upsert 接收的定义不合法。
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EngineChangeError {
    EmptyId,
}
pub struct FormulaEngine {
    inner: FormulaEngineInner,
}
impl FormulaEngine {
    /// allows:
    /// - 任意定义顺序。
    /// - 保存存在语法/类型错误、缺失依赖、未就绪依赖或依赖环的公式定义。
    ///
    /// errors:
    /// - ID 为空。
    /// - ID 重复。
    pub fn new(schema: FormulaSchema) -> Result<Self, FormulaEngineInitError> {
        Self::new_impl(schema)
    }
    pub fn property(&self, id: &PropertyId) -> Option<PropertyState> {
        Self::property_impl(self, id)
    }
    pub fn properties(&self) -> Vec<PropertyState> {
        Self::properties_impl(self)
    }
    pub fn state(&self) -> FormulaEngineState<'_> {
        Self::state_impl(self)
    }
    /// 原子更新 PropertyDefinition。
    /// 返回前重新分析该 ID 的直接、间接公式依赖者及新的 Formula 定义。
    ///
    /// no-op: 定义内容没有发生变化。
    ///
    /// allows:
    /// - 同一 ID 的 Input 与 Formula 互换。
    /// - 保存存在语法/类型错误、缺失依赖、未就绪依赖或依赖环的公式定义。
    ///
    /// error: ID 为空串。
    pub fn upsert(
        &mut self,
        property: PropertyDefinition,
    ) -> Result<FormulaEngineChangeResult, EngineChangeError> {
        Self::upsert_impl(self, property)
    }
    /// 删除后，仍依赖该 ID 的公式变为 NotReady。
    pub fn remove(&mut self, id: &PropertyId) -> Option<FormulaEngineChangeResult> {
        Self::remove_impl(self, id)
    }
}
