// Generated by md-first. DO NOT EDIT.
// Source: docs/specs/formula-engine.md

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaSchema {
    pub properties: Vec<PropertyDefinition>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PropertyDefinition {
    Input { id: PropertyId, ty: ValueType },
    Formula(FormulaDefinition),
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaDefinition {
    pub id: PropertyId,
    /// Formula expression; prop("id") references another Property by ID in the same FormulaSchema.
    pub expression: String,
}
/// Stable ID assigned by the caller.
///
/// - Input and Formula share a namespace; Engine validates that IDs are nonempty and unique within FormulaSchema.
/// - No string-format restrictions; case-sensitive, without Unicode normalization.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, derive_more::From)]
#[from(String, &str)]
pub struct PropertyId(pub String);
/// Declared types for Inputs and inferred types for Formulas.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ValueType {
    /// See [Current Number](formula-language.md#current-number) for numeric behavior.
    Number,
    String,
    Boolean,
    Date,
    /// Static type is undetermined; allowed in Input declarations and inferred types, including nested types.
    /// Accepts any Value variant at this position; operations check the concrete type at runtime.
    Unknown,
    List(Box<ValueType>),
    Union(Vec<ValueType>),
}
#[derive(Debug, PartialEq, Eq)]
pub enum FormulaEngineState<'a> {
    /// No cycles, and every formula is Ready.
    AllReady,
    /// Other formulas may remain Ready when one formula is not.
    NotAllReady {
        /// Returns one cycle when present; each ID directly depends on the next, and the first and last IDs are equal.
        /// - empty: No cycle, but some formulas are not Ready.
        /// - [A, A]: Self-reference A -> A
        /// - [A, B, C, A]: Cycle A -> B -> C -> A
        cycle_path: &'a [PropertyId],
    },
}
/// Independent snapshot of a property definition and its state; later Engine updates do not change it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PropertyState {
    Input { id: PropertyId, ty: ValueType },
    Formula(FormulaState),
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaState {
    pub definition: FormulaDefinition,
    pub status: FormulaStatus,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FormulaStatus {
    /// The formula and its dependencies are executable.
    /// output_type may contain Unknown; for example, [] is Ready with type List(Unknown).
    Ready { output_type: ValueType },
    NotReady,
}
/// Result of a FormulaEngine::upsert / remove change.
#[derive(Debug, PartialEq, Eq)]
pub struct FormulaEngineChangeResult {
    /// Formula IDs affected by this change, including direct and transitive dependents.
    /// - Includes only Formulas that still exist after the change.
    /// - When upsert adds or changes a Formula, includes that Formula itself.
    /// - Empty when the definition has not changed.
    pub affected_formulas: Vec<PropertyId>,
}
/// Invalid definitions supplied to FormulaEngine::new.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FormulaEngineInitError {
    EmptyId,
    DuplicateId(PropertyId),
}
/// Invalid definition supplied to FormulaEngine::upsert.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EngineChangeError {
    EmptyId,
}
pub struct FormulaEngine {
    inner: FormulaEngineInner,
}
impl FormulaEngine {
    /// allows:
    /// - Definitions in any order.
    /// - Saving formula definitions with syntax/type errors, missing or unready dependencies, or dependency cycles.
    ///
    /// errors:
    /// - Empty ID.
    /// - Duplicate ID.
    pub fn new(schema: FormulaSchema) -> Result<Self, FormulaEngineInitError> {
        Self::new_impl(schema)
    }
    pub fn property(&self, id: &PropertyId) -> Option<PropertyState> {
        Self::property_impl(self, id)
    }
    pub fn properties(&self) -> Vec<PropertyState> {
        Self::properties_impl(self)
    }
    pub fn state(&self) -> FormulaEngineState<'_> {
        Self::state_impl(self)
    }
    /// Returns Ok(EvaluateResult) once input validation passes, even if every requested formula fails.
    /// Formula and row errors are returned with the result; other formulas continue.
    ///
    /// allows: NotReady formulas in formula_ids.
    ///
    /// error: Any input validation failure prevents all formula evaluation; only one EvaluateInputError is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use formula_engine::{Column, ColumnData, EvaluateInput, FormulaDefinition, FormulaEngine,
    ///     FormulaEngineState, FormulaSchema, NullBuffer, PropertyDefinition, PropertyId, RuntimeContext, ValueType};
    /// use std::collections::HashMap;
    /// use std::time::{SystemTime, UNIX_EPOCH};
    ///
    /// // 1. Define schema
    /// let schema = FormulaSchema {
    ///     properties: vec![
    ///         PropertyDefinition::Input { id: "text".into(), ty: ValueType::String },
    ///         PropertyDefinition::Input { id: "number".into(), ty: ValueType::Number },
    ///         PropertyDefinition::Formula(FormulaDefinition {
    ///             id: "formula".into(),
    ///             expression: r#"repeat(prop("text"), prop("number"))"#.into(),
    ///         }),
    ///     ],
    /// };
    ///
    /// // 2. Create the engine
    /// let engine = FormulaEngine::new(schema).expect("valid definitions");
    /// assert!(matches!(engine.state(), FormulaEngineState::AllReady));
    ///
    /// // 3. Capture one runtime snapshot (this example uses UTC+08:00)
    /// let since_epoch = SystemTime::now()
    ///     .duration_since(UNIX_EPOCH)
    ///     .expect("system clock is before Unix epoch");
    /// let runtime = RuntimeContext {
    ///     now: since_epoch.as_millis().try_into().expect("timestamp exceeds i64"),
    ///     time_zone: "+08:00".into(), // Use the business/user time zone's offset.
    /// };
    ///
    /// // 4. Build input columns in row_ids order
    /// // row_id    text    number
    /// // row-1     "ha"    2
    /// // row-2     "go"    3
    /// let input = EvaluateInput {
    ///     row_ids: vec!["row-1".into(), "row-2".into()],
    ///     columns: HashMap::from([
    ///         (
    ///             "text".into(),
    ///             Column::String(ColumnData {
    ///                 values: vec!["ha".into(), "go".into()],
    ///                 validity: NullBuffer::new_valid(2),
    ///             }),
    ///         ),
    ///         (
    ///             "number".into(),
    ///             Column::Number(ColumnData {
    ///                 values: vec![2.0, 3.0],
    ///                 validity: NullBuffer::new_valid(2),
    ///             }),
    ///         ),
    ///     ]),
    ///     runtime,
    ///     formula_ids: vec!["formula".into()],
    /// };
    ///
    /// // 5. Evaluate the requested formula
    /// let result = engine.evaluate(&input).expect("valid request");
    ///
    /// // 6. Read the result column in row_ids order
    /// let Some(Ok(output)) = result.formulas.get(&PropertyId::from("formula")) else {
    ///     panic!("expected a computed formula");
    /// };
    /// let Column::String(column) = &output.column else {
    ///     panic!("expected a string column");
    /// };
    /// assert_eq!(column.values, ["haha", "gogogo"]);
    /// assert!(output.errors.is_empty());
    /// ```
    pub fn evaluate(
        &self,
        input: &EvaluateInput,
    ) -> Result<EvaluateResult, EvaluateInputError> {
        Self::evaluate_impl(self, input)
    }
    /// Atomically updates PropertyDefinition.
    /// Reanalyzes direct and transitive formula dependents of this ID, and the new Formula definition, before returning.
    ///
    /// no-op: The definition has not changed.
    ///
    /// allows:
    /// - Switching the same ID between Input and Formula.
    /// - Saving formula definitions with syntax/type errors, missing or unready dependencies, or dependency cycles.
    ///
    /// error: Empty ID string.
    pub fn upsert(
        &mut self,
        property: PropertyDefinition,
    ) -> Result<FormulaEngineChangeResult, EngineChangeError> {
        Self::upsert_impl(self, property)
    }
    /// After removal, formulas that still depend on this ID become NotReady.
    pub fn remove(&mut self, id: &PropertyId) -> Option<FormulaEngineChangeResult> {
        Self::remove_impl(self, id)
    }
}
