// Generated by md-first. DO NOT EDIT.
// Source: docs/specs/formula-engine.md

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaSchema {
    pub properties: Vec<PropertyDefinition>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PropertyDefinition {
    Input { id: PropertyId, ty: ValueType },
    Formula(FormulaDefinition),
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaDefinition {
    pub id: PropertyId,
    /// Formula expression; prop("id") references another Property by ID in the same FormulaSchema.
    pub expression: String,
}
/// Stable ID assigned by the caller.
///
/// - Input and Formula share a namespace; Engine validates that IDs are nonempty and unique within FormulaSchema.
/// - No string-format restrictions; case-sensitive, without Unicode normalization.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, derive_more::From)]
#[from(String, &str)]
pub struct PropertyId(pub String);
/// Declared types for Inputs and inferred types for Formulas.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ValueType {
    /// See [Planned Number](formula-language.md#planned-number) for numeric behavior.
    Number,
    String,
    Boolean,
    Date,
    /// Static type is undetermined; allowed in Input declarations and inferred types, including nested types.
    /// Accepts any Value variant at this position; operations check the concrete type at runtime.
    Unknown,
    List(Box<ValueType>),
    Union(Vec<ValueType>),
}
#[derive(Debug, PartialEq, Eq)]
pub enum FormulaEngineState<'a> {
    /// No cycles, and every formula is Ready.
    AllReady,
    /// Other formulas may remain Ready when one formula is not.
    NotAllReady {
        /// Returns one cycle when present; each ID directly depends on the next, and the first and last IDs are equal.
        /// - empty: No cycle, but some formulas are not Ready.
        /// - [A, A]: Self-reference A -> A
        /// - [A, B, C, A]: Cycle A -> B -> C -> A
        cycle_path: &'a [PropertyId],
    },
}
/// Independent snapshot of a property definition and its state; later Engine updates do not change it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PropertyState {
    Input { id: PropertyId, ty: ValueType },
    Formula(FormulaState),
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaState {
    pub definition: FormulaDefinition,
    pub status: FormulaStatus,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FormulaStatus {
    /// The formula and its dependencies are executable.
    /// output_type may contain Unknown; for example, [] is Ready with type List(Unknown).
    Ready { output_type: ValueType },
    NotReady,
}
/// Result of a FormulaEngine::upsert / remove change.
#[derive(Debug, PartialEq, Eq)]
pub struct FormulaEngineChangeResult {
    /// Formula IDs affected by this change, including direct and transitive dependents.
    /// - Includes only Formulas that still exist after the change.
    /// - When upsert adds or changes a Formula, includes that Formula itself.
    /// - Empty when the definition has not changed.
    pub affected_formulas: Vec<PropertyId>,
}
/// Invalid definitions supplied to FormulaEngine::new.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FormulaEngineInitError {
    EmptyId,
    DuplicateId(PropertyId),
}
/// Invalid definition supplied to FormulaEngine::upsert.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EngineChangeError {
    EmptyId,
}
pub struct FormulaEngine {
    inner: FormulaEngineInner,
}
impl FormulaEngine {
    /// allows:
    /// - Definitions in any order.
    /// - Saving formula definitions with syntax/type errors, missing or unready dependencies, or dependency cycles.
    ///
    /// errors:
    /// - Empty ID.
    /// - Duplicate ID.
    pub fn new(schema: FormulaSchema) -> Result<Self, FormulaEngineInitError> {
        Self::new_impl(schema)
    }
    pub fn property(&self, id: &PropertyId) -> Option<PropertyState> {
        Self::property_impl(self, id)
    }
    pub fn properties(&self) -> Vec<PropertyState> {
        Self::properties_impl(self)
    }
    pub fn state(&self) -> FormulaEngineState<'_> {
        Self::state_impl(self)
    }
    /// Atomically updates PropertyDefinition.
    /// Reanalyzes direct and transitive formula dependents of this ID, and the new Formula definition, before returning.
    ///
    /// no-op: The definition has not changed.
    ///
    /// allows:
    /// - Switching the same ID between Input and Formula.
    /// - Saving formula definitions with syntax/type errors, missing or unready dependencies, or dependency cycles.
    ///
    /// error: Empty ID string.
    pub fn upsert(
        &mut self,
        property: PropertyDefinition,
    ) -> Result<FormulaEngineChangeResult, EngineChangeError> {
        Self::upsert_impl(self, property)
    }
    /// After removal, formulas that still depend on this ID become NotReady.
    pub fn remove(&mut self, id: &PropertyId) -> Option<FormulaEngineChangeResult> {
        Self::remove_impl(self, id)
    }
}
