// Generated by md-first. DO NOT EDIT.
// Source: docs/specs/ide.md

use crate::{FormulaDefinition, FormulaEngine, PropertyId, ValueType};
pub use analyzer::{Span, TextEdit, Token};
pub use ide::{
    CompletionConfig, CompletionItem, CompletionKind, CompletionResult, DisplaySegment,
    SignatureHelp, SignatureItem,
};
/// Analyzes through a shared borrow of Engine; dependencies with the same ID are
/// computed from the definition currently being edited.
/// Multiple Drafts can be created from the same Engine at once; all Draft borrows
/// must end before saving.
#[derive(Debug)]
pub struct FormulaDraft<'engine> {
    inner: FormulaDraftInner<'engine>,
}
impl FormulaDraft<'_> {
    pub fn state(&self) -> &FormulaDraftState {
        Self::state_impl(self)
    }
    /// Queries completion, postfix completion, and signature help together.
    /// Candidates that would create a dependency cycle are still returned, but marked disabled.
    /// CompletionConfig::default() has preferred_limit 5; 0 disables preferred_indices.
    pub fn help(&self, cursor: TextOffset, config: CompletionConfig) -> CursorHelp {
        Self::help_impl(self, cursor, config)
    }
    /// Returns edits attached to a diagnostic as suggestions; an unknown or non-current ID returns an empty list.
    pub fn quick_fixes(&self, diagnostic_id: &DiagnosticId) -> Vec<QuickFix> {
        Self::quick_fixes_impl(self, diagnostic_id)
    }
    /// Returns a replacement edit for the entire expression; lexer/parser diagnostics prevent formatting, but semantic errors do not.
    pub fn format_edits(&self) -> Result<FormulaEdit, FormatError> {
        Self::format_edits_impl(self)
    }
    /// Atomically updates the expression and all analysis fields in state() before returning.
    ///
    /// - allow: an invalid expression; inspect diagnostics through state().
    /// - error: validation of the Edits version, ranges, cursor, or non-overlap fails; Draft remains unchanged.
    pub fn update_expression(
        &mut self,
        update: ExpressionUpdate,
    ) -> Result<UpdateExpressionResult, UpdateExpressionError> {
        Self::update_expression_impl(self, update)
    }
    /// Does not automatically commit; when saving, pass the returned definition to FormulaEngine::upsert.
    pub fn into_definition(self) -> FormulaDefinition {
        Self::into_definition_impl(self)
    }
}
/// UTF-8 byte offset.
#[derive(Clone, Copy, Debug, PartialEq, Eq, derive_more::From)]
pub struct TextOffset(pub usize);
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DraftVersion(pub u64);
/// Independent snapshot; later Draft updates do not change it.
#[derive(Clone, Debug)]
pub struct FormulaDraftState {
    /// Starts at 0; incremented by 1 when Replace changes text or Edits succeeds.
    pub version: DraftVersion,
    pub definition: FormulaDefinition,
    /// - Returns the root expression's inferred type, even with local syntax errors.
    /// - Uses Unknown for undetermined types, e.g. [] → List(Unknown).
    /// - An empty expression → Unknown.
    pub output_type: ValueType,
    /// Syntax and semantic diagnostics, independent of cursor; includes direct and indirect self-reference problems.
    pub diagnostics: Vec<ExpressionDiagnostic>,
    /// Lexical tokens of the current definition.expression, retaining comments, newlines, and Eof.
    pub tokens: Vec<Token>,
    /// Complete prop("id") calls in source order, including repeats and unresolved IDs.
    /// Excludes strings, comments, malformed calls, and unsupported member calls.
    pub property_references: Vec<PropertyReference>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PropertyReference {
    /// Decoded string literal; existence and readiness remain separate diagnostics.
    pub property_id: PropertyId,
    /// The whole call, including internal whitespace and comments.
    pub span: Span,
    /// The quoted ID literal only; replacing this span preserves the call's trivia.
    pub id_span: Span,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ExpressionDiagnostic {
    pub id: DiagnosticId,
    /// Location in the current Draft's expression.
    pub span: Span,
    pub message: String,
}
/// Opaque ID belonging to one Draft revision; an ID from another Draft or revision is not current.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct DiagnosticId(pub String);
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CursorHelp {
    /// Use this version as FormulaEdit.base_version when applying this completion's edits.
    pub base_version: DraftVersion,
    pub completion: CompletionResult,
    pub signature_help: Option<SignatureHelp>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormulaEdit {
    /// Must equal the current state.version, preventing stale edits from being applied to a modified expression.
    pub base_version: DraftVersion,
    /// All ranges are based on the expression before modification and must not overlap.
    pub edits: Vec<TextEdit>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ExpressionUpdate {
    /// Replaces the current expression; base_version is not required.
    Replace(String),
    Edits {
        edit: FormulaEdit,
        /// Coordinates in the expression before modification, relocated according to the edits.
        cursor: TextOffset,
    },
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct QuickFix {
    pub title: String,
    /// version is bound to the Draft that produced the diagnostic.
    pub edit: FormulaEdit,
}
#[derive(Clone, Debug)]
pub struct UpdateExpressionResult {
    pub state: FormulaDraftState,
    /// Replace returns the new expression.len(); for an empty string this is 0. Edits returns the relocated coordinate.
    pub cursor: TextOffset,
}
/// The expression contains a lexer/parser diagnostic and cannot be formatted.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FormatError;
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UpdateExpressionError {
    VersionMismatch,
    /// Out of bounds or not on a UTF-8 character boundary.
    InvalidCursor,
    /// Reversed or out-of-bounds range, or an endpoint not on a UTF-8 character boundary.
    InvalidEditRange,
    OverlappingEdits,
}
