// Generated by md-first. DO NOT EDIT.
// Source: docs/specs/wasm-api.md

use wasm_bindgen::prelude::*;
/// One owned Engine and its Draft handles; all domain work runs in Rust.
/// Explicit close is idempotent. The host must release the generated allocation
/// with free() after closing and must not use the allocation after free().
#[wasm_bindgen]
pub struct FormulaEngineSession {
    inner: FormulaEngineSessionInner,
}
#[wasm_bindgen]
impl FormulaEngineSession {
    /// Constructs an Engine from the lossless FormulaSchema DTO.
    #[wasm_bindgen(constructor)]
    pub fn new(schema: JsValue) -> Result<FormulaEngineSession, JsValue> {
        Self::new_impl(schema)
    }
    pub fn get_property(&self, id: String) -> Result<JsValue, JsValue> {
        Self::get_property_impl(self, id)
    }
    pub fn get_properties(&self) -> Result<JsValue, JsValue> {
        Self::get_properties_impl(self)
    }
    pub fn get_state(&self) -> Result<JsValue, JsValue> {
        Self::get_state_impl(self)
    }
    /// Accepts PropertyId[] and returns PropertyId[] with FormulaEngine::required_inputs semantics.
    /// Malformed arrays reject with INVALID_DTO; formula-selection errors use EVALUATE_INPUT.
    /// Available while Drafts are active; Engine close rejects with ENGINE_CLOSED.
    pub fn required_inputs(&self, formula_ids: JsValue) -> Result<JsValue, JsValue> {
        Self::required_inputs_impl(self, formula_ids)
    }
    /// Rejects ACTIVE_DRAFTS while any Draft handle exists.
    pub fn upsert(&mut self, property: JsValue) -> Result<JsValue, JsValue> {
        Self::upsert_impl(self, property)
    }
    /// Rejects ACTIVE_DRAFTS while any Draft handle exists.
    pub fn remove(&mut self, id: String) -> Result<JsValue, JsValue> {
        Self::remove_impl(self, id)
    }
    pub fn evaluate(&self, input: JsValue) -> Result<JsValue, JsValue> {
        Self::evaluate_impl(self, input)
    }
    pub fn create_draft(&mut self, formula: JsValue) -> Result<u32, JsValue> {
        Self::create_draft_impl(self, formula)
    }
    pub fn draft_state(&self, handle: u32) -> Result<JsValue, JsValue> {
        Self::draft_state_impl(self, handle)
    }
    /// Cursor is validated as a finite unsigned 32-bit integer before UTF-16 conversion.
    pub fn draft_help(
        &self,
        handle: u32,
        cursor: JsValue,
        config: JsValue,
    ) -> Result<JsValue, JsValue> {
        Self::draft_help_impl(self, handle, cursor, config)
    }
    pub fn draft_quick_fixes(
        &self,
        handle: u32,
        diagnostic_id: String,
    ) -> Result<JsValue, JsValue> {
        Self::draft_quick_fixes_impl(self, handle, diagnostic_id)
    }
    pub fn draft_format_edits(&self, handle: u32) -> Result<JsValue, JsValue> {
        Self::draft_format_edits_impl(self, handle)
    }
    pub fn draft_update_expression(
        &mut self,
        handle: u32,
        update: JsValue,
    ) -> Result<JsValue, JsValue> {
        Self::draft_update_expression_impl(self, handle, update)
    }
    /// Consumes the Draft; no saved definition is changed.
    pub fn draft_into_definition(&mut self, handle: u32) -> Result<JsValue, JsValue> {
        Self::draft_into_definition_impl(self, handle)
    }
    /// Discards this Draft. Repeated close and close after Engine close succeed.
    pub fn draft_close(&mut self, handle: u32) {
        Self::draft_close_impl(self, handle)
    }
    /// Releases all Drafts before releasing Engine; repeated close succeeds.
    pub fn close(&mut self) {
        Self::close_impl(self)
    }
}
